openapi: 3.0.0
info:
  version: 6.0.0
  title: Commercial Instructions Schema
  description: Commercial Instructions Schema
  termsOfService: http://placeholderdomain.io/terms/
  contact:
    name: TIP Initiative
    email: tipinitiative@frontrowadvisory.com
    url: http://placeholderdomain.io
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
paths: {}
components:
  schemas:
    BuyerCommercialInstructions:
      description: >-
        Schema provides for the definition of detailed Commercial Instructions including
        patterns, rotations, weight
      properties:
        transactionHeader:
          $ref: 'commonSchemas.yaml#/components/schemas/TransactionHeader'
        referenceIds:
          description: >-
            Array of ReferenceId objects containing the order id references; may also contain
            originating RFP and Proposal id references
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/ReferenceId'
          minItems: 1
        buyer:
          $ref: 'commonSchemas.yaml#/components/schemas/Buyer'
        contacts:
          description: Array of contact objects
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/Contact'
        advertiser:
          $ref: 'commonSchemas.yaml#/components/schemas/Advertiser'
        product:
          $ref: 'commonSchemas.yaml#/components/schemas/Product'
        dateWindow:
          $ref: 'commonSchemas.yaml#/components/schemas/DateWindow'
        cpeCode:
          $ref: 'commonSchemas.yaml#/components/schemas/CpeCode'
        instructionComment:
          description: Comments pertaining to overall instructions
          type: string
        externalComment:
          description: Free form text to accommodate transaction comments and/or activities outside the TIP flow
          type: string
        instructionType:
          description: >-
            Instruction Type associated to the instructions that applies to how the AD ID should
            be applied to units
          type: string
          enum:
            - Rotation Share
            - Pattern
            - Unit Specific
        instructionDetails:
          type: array
          items:
            $ref: '#/components/schemas/InstructionDetail'
      required:
        - transactionHeader
        - referenceIds
        - advertiser
        - product
        - dateWindow
        - instructionType
    InstructionDetail:
      description: Commercial Instruction details for instruction type
      properties:
        actionType:
          description: Action for the instruction detail
          type: string
          enum:
            - New
            - Change
            - Cancel
        inventoryTypes:
          type: array
          items:
            type: string
        mediaOutlet:
          $ref: 'commonSchemas.yaml#/components/schemas/MediaOutlet'
        creative:
          $ref: 'commonSchemas.yaml#/components/schemas/Creative'
        brand:
          $ref: 'commonSchemas.yaml#/components/schemas/Brand'
        product:
          $ref: 'commonSchemas.yaml#/components/schemas/Product'
        linkType:
          $ref: 'commonSchemas.yaml#/components/schemas/LinkType'
        deliveryDate:
          description: Material copy delivery date
          type: string
          format: date
        deliveryService:
          description: Delivery service that will supply the the creative material
          type: string
        timePeriods:
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/TimePeriod'
        rotationShare:
          description: >-
            If instruction type equals 'Rotation', this will be the percentage assignment to
            be applied to each creativeId
          type: integer
        patternInstruction:
          description: >-
            If instruction type equal 'Pattern', this will be the pattern assignments to be applied
            to each creative; for example A,B,B,C represents how the creative  A, B and C should
            be sequentially assigned to units
          type: string
        unitSpecificInstructions:
          description: >-
            If instruction type equal 'Unit Specific', this will the list of unitIds that are
            valid for the creative
          type: array
          items:
            type: string
        specialInstructions:
          description: Comments that pertain to the instruction details
          type: string
      required:
        - actionType
        - mediaOutlet
        - creative
        - deliveryService
    SellerCommercialInstructions:
      description: Schema is an alias to perform actions CancelConfirmRecallReject
      $ref: 'commonSchemas.yaml#/components/schemas/CancelConfirmRecallReject'
