openapi: 3.0.0
info:
  version: 5.1.0
  title: Commercial Instructions Schema
  description: Commercial Instructions Schema
  termsOfService: http://placeholderdomain.io/terms/
  contact:
    name: TIP Initiative
    email: tipinitiative@frontrowadvisory.com
    url: http://placeholderdomain.io
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
paths: {}
components:
  schemas:
    BuyerCommercialInstructions:
      oneOf:
        - $ref: '#/components/schemas/BuyerCommercialInstructionsObj'
        - $ref: 'commonSchemas.yaml#/components/schemas/CancelConfirmRecallReject'
    BuyerCommercialInstructionsObj:
      description: Top level element for Commercial Instructions Buyer POST operations
      properties:
        transactionHeader:
          $ref: 'commonSchemas.yaml#/components/schemas/TransactionHeader'
        referenceIds:
          description: >-
            Information pertaining to all the ids and their sources that are associated to the order;
            this may include order ids, proposal ids, etc. Order ID is required
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/ReferenceId'
        buyer:
          $ref: 'commonSchemas.yaml#/components/schemas/Buyer'
        contact:
          description: Array of Contacts Information
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/Contact'
        advertiser:
          $ref: 'commonSchemas.yaml#/components/schemas/Advertiser'
        product:
          $ref: 'commonSchemas.yaml#/components/schemas/Product'
        dateWindow:
          $ref: 'commonSchemas.yaml#/components/schemas/DateWindow'
        cpeCode:
          $ref: 'commonSchemas.yaml#/components/schemas/CpeCode'
        instructionComment:
          description: Comments pertaining to overall instructions
          type: string
        externalComment:
          description: Free form text to accommodate transaction comments and/or activities outside the
            TIP flow
          type: string
        instructionType:
          description: >-
            Instruction Type associated to the instructions that applies to how the AD ID should be applied
            to units
          type: string
          enum:
            - Rotation Share
            - Pattern
            - Unit Specific
        instructionDetails:
          type: array
          items:
            $ref: '#/components/schemas/InstructionDetail'
      required:
        - transactionHeader
        - referenceIds
        - advertiser
        - product
        - dateWindow
        - instructionType
    InstructionDetail:
      description: Commercial Instruction details for instruction type
      properties:
        actionType:
          description: Action for instruction detail
          type: string
          enum:
            - New
            - Revised
            - Cancelled
        inventoryTypes:
          description: Valid Inventory Types for the instructions
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/InventoryType'
        mediaOutlet:
          $ref: 'commonSchemas.yaml#/components/schemas/MediaOutlet'
        adId:
          description: A unique identifier for commercial copy
          type: string
        name:
          description: Creative title associated to AD-ID
          type: string
        brand:
          $ref: 'commonSchemas.yaml#/components/schemas/Brand'
        product:
          $ref: 'commonSchemas.yaml#/components/schemas/Product'
        length:
          description: Commercial length associated to AD-ID
          type: integer
        linkType:
          $ref: 'commonSchemas.yaml#/components/schemas/LinkType'
        deliveryDate:
          description: Material Commercial delivery date
          type: string
          format: date
        deliveryService:
          description: Delivery service that will supply the the Ad-ID
          type: string
        timePeriods:
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/TimePeriod'
        rotationShare:
          description: >-
            If instruction type equals "Rotation" - this will be the percentage assignment to be applied
            to each AD-ID; the total across all AD-ID's should equal to 100%
          type: integer
        patternInstruction:
          description: >-
            If instruction type equal "Pattern" -this will be the pattern assignments to be applied to
            each AD-ID; for example A,B,B,C represents how AD-ID A, B and C should be sequentially assigned
            to units
          type: string
        unitSpecificInstruction:
          description: >-
            If instruction type equal "Unit Specific" = this will the list of unit id's that are valid
            for the AD-ID
          type: array
          items:
            type: string
        specialInstructions:
          description: Comments that pertain to the instruction details
          type: string
      required:
        - actionType
        - mediaOutlet
        - adId
        - length
        - deliveryService
