openapi: "3.0.0"
info:
  version: 1.0.1
  title: Common Schemas
  description: Common Schemas, based on TIP 4.0 documentation
  termsOfService: http://placeholderdomain.io/terms/ # TODO
  contact:
    name: TIP Initiative
    email: tipinitiative@frontrowadvisory.com
    url: http://placeholderdomain.io # TODO
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT # TODO 

paths: {} # no paths

components:
  schemas:

    commonPayloadHeader:
      description: Common properties to be included with all payloads
      required:
        - tipVersion
        - transactionNum
        - timeStamp
      properties:
        tipVersion:
          description: TIP version of the interface
          type: string  # TODO any constraints?
        transactionId:
          description: Buyer or Seller generated unique value for transaction
          type: string  # TODO any constraints?
        timeStamp: 
          description: Date and time the transaction was created
          type: string # TODO should this be expressed as an Epoch date instead (32 bit integer)?
          format: date-time
          
    encodededPayloadWrapper:
      description: Used with non-JSON payload formats such as TVB 3.2 or DARE, provides information about the payload and it's encoding
      required:
        - CommonPayloadHeader
        - payloadData
        - payloadType
        - payloadEncoding
      properties:
        CommonPayloadHeader:
          $ref: '#/components/schemas/commonPayloadHeader'
        payloadData:
          description: The encoded payload data
          type: string
        payloadType:
          description: Format of the payload data
          type: string
          enum: [TVB3.2, DARE]
        payloadEncoding: 
          description: Encoding method used on the payload data
          type: string
          enum: [Base64]

    subscriptionRequest:
      description: A client creates a subscription by issuing a request against the subscriptions resource. The subscription namespace is client-defined via the POST operation.
      required:
        - resource
        - notificationUrl
      properties:
        resource:
          description: Resource path to watch
          type: string
          format: uri
        notificationUrl:
          description: The target web hook URL
          type: string
          format: uri
        clientState:
          description: Opaque string passed back to the client on all notifications. Callers may choose to use this to provide tagging mechanisms.
          type: string

    subscriptionResponse:
      description: If the subscription was successfully created, the service MUST respond with the status code 201 CREATED and a body containing at least the following properties
      required:
        - id
      properties:
        id:
          description: Unique ID of the new subscription that can be used later to update/delete the subscription.
          type: string
        expirationDateTime:
          description: The expiration date of the subscription
          type: string
          format: date-time

    transactionHeader:
      description: Transaction header details
      required:
        - tipVersion
        - transactionNum
        - transactionType
        - sourceID
        - sourceName
        - timeStamp
      properties:
        tipVersion:
          description: TIP version of the interface
          type: string  # TODO any constraints?
        transactionNum:
          description: Buyer or Seller generated unique number for transaction
          type: integer
          format: int64
        transactionType:
          description: Indicates the type of transaction (New, Changed, Cancelled)
          type: string
          enum: [New, Changed, Cancelled]
        sourceId: 
          description: String	Indicates the source "trading partner" unique identification  
          type: string # TODO any constraints?
        sourceName:
          description: Indicates the source "trading partner" name
          type: string
        timeStamp: 
          description: Date and time the transaction was created
          type: string # TODO should this be expressed as an Epoch date instead (32 bit integer)?
          format: date-time

    mediaOutlet:
      description: Combines a unique identifier and name into a single object # TODO generic description
      required:
        - mediaOutletId
        - mediaOutletName
        - mediaOutletType
      properties:
        mediaOutletId:
          description: Unique persistent identifier for the station or network
          type: string  # TODO any constraints?
        mediaOutletName:
          description: Station or network name associated to mediaOutletId
          type: string  # TODO any constraints?
        mediaOutletType:
          description: Type of media outlet
          type: string
          enum: [Broadcast TV, OTT, Connected TV, Addressable TV, Digital Video, Mobile Video, Terrestrial Radio, Digital Audio] 
        mediaOutletChannel:
          description: String	Station or network station identification (Channel) 
          type: string  # TODO any constraints?
        mediaOutletMarketName:
          type: string
        mediaOutletReference:
          description: Buyer external mediaoutlet reference information
          type: string
    Advertiser:
      description: Combines a unique identifier and name into a single object # TODO generic description
      required:
        - advertiserId
        - advertiserName
      properties:
        advertiserId:
          description: Unique persistent identifier for the advertiser/client
          type: string  # TODO any constraints?
        advertiserName:
          description: String	Advertiser name 
          type: string  # TODO any constraints?
        advertiserReference:
          type: string
    Buyer:
      description: Packages a unique identifier and name into a single object # TODO generic description
      required:
        - buyerId
        - buyerName
      properties:
        buyerId:
          description: Unique persistent identifier for the Buying organization or  trafficking agency and /or the supplier of the media
          type: string  # TODO any constraints?
        buyerName:
          description: Buying organization name and location
          type: string  # TODO any constraints?
        buyerReference:
          type: string
    Product:
      description: Combines a unique identifier, name, and reference into an object # TODO generic description
      required:
        - productId
        - productName
      properties:
        productId:
          description: Unique persistent identifier for the product
          type: string  # TODO any constraints?
        productName:
          description: Brand Name
          type: string  # TODO any constraints?
        productReference:
          type: string

    audienceSegment:
      description: Combines a unique identifier and name into a single object # TODO generic description
      required:
        - audienceSegmentId
        - audienceSegmentName
        - audienceSegmentReference
        - ratingSource
        - ratingStream
        - viewershipType
        - universeType
        - primaryIndicator
        - Guarantee
      properties:  
        audienceSegmentId:
          description: Unique persistent identifier for audience segment
          type: string  # TODO any constraints?
        audienceSegmentName:
          description: Audience Segment Name 
          type: string  # TODO any constraints?
        audienceSegmentReference:
          description: Buyer external audience segment reference
          type: string  # TODO any constraints?
        ratingSource:
          description: Unique identifier for audience segment
          type: string
          enum: [Nielsen, ComScore] # TODO is Custom a constant?
        ratingStream:
          description: Audience Segment Name 
          type: string  
          enum: [Program Live, C3, C7] # TODO is Custom a constant?
        viewershipType:
          description: Type of viewership elements
          type: string  
          enum: [VPVH, Composition, Reach, Frequency] # TODO is Custom a constant?
        universeType:
          description: Type of universe
          type: string  
          enum: [Market, Total US, Coverage] # TODO is Custom a constant?
        primaryIndicator:
          description: todo # TODO need description
          type: boolean
        Guarantee:
          description: todo # TODO need description
          type: boolean

    audienceMetric: # TODO schema and property have the same name
      description: Combines audience segment metric attributes into single object
      properties:
        audienceSegmentId:
          description: List of pricing metric segments (AND) # TODO AND what? should there be additional data besides the array of enums specified here?
          type: array
          items:
            type: string 
            enum: [CPM, CPP] # TODO is Custom a constant?
        audienceMetricValue:
          description: Audience metric dollar value
          type: number
          format: float

    cancellationTerms:
      description: Combines cancellation options data attributes into a single object
      required:
        - cancellationType
        - Cancellation
        - cancellationPriorDays
        - cancellationPercentage
      properties:
        cancellationType:
          description: Type of Cancellation elements
          type: string 
          enum: [Quarterly Option, Rolling Options] 
        Cancellation:
          description: Quarter name or broadcast date dependent on cancellation type
          oneOf:
            - type: string
            - type: string
              format: date-time # TODO is broadcast date a date-time string?
        cancellationPriorDays:
          description: Number of days notice needed prior to start quarter or broadcast date to request cancellation
          type: integer #TODO any constraints on this?
          format: int32
        cancellationPercentage:
          description: Number of days notice needed prior to start quarter or broadcast date to request cancellation
          type: number #TODO any constraints on this?
          format: float

    referenceIds:
      description: Combines the system ids across mulitple systems into a single object
      required:
        - referenceSourceName
        - referenceSourceId
        - referenceType
        - referenceId
      properties:
        referenceSourceName:
          description: Name associated with the organization that is supplying the ids and version information
          type: string #TODO any constraints on this?
        referenceSourceId:
          type: string
        referenceSourceLookup:
          description: Reference Source Look up; this could be URI to lookup information about the reference source name
          type: string #TODO any constraints on this?
        referenceType:
          description: The type of IDs that are being supplied  
          type: string 
          enum: [RFP, Proposal, Order, Invoice] 
        referenceId:
          description: Number or ID associated with reference type(s) 
          oneOf:
            - type: number #TODO any constraints on this?
            - type: string #TODO any constraints on this?
        referenceVersionId:
          description: Version Number to indicate what version  of the reference id
          type: string #TODO description says version number, should this be a number? any constraints?
        ReferenceName:
          description: Free form name used to identify the type of entity such as Order Name, RFP Name
          type: string #TODO any constraints?

    cpeCode: 
      description: Combines audience segment metric attributes into single object
      properties:
        clientCode:
          description: Client code provided from the buyer. Packages client, product and estimate codes together.
          type: string
        productCode:
          description: Product code provided from the buyer. Packages client, product and estimate codes together.
          type: string
        estimateCode:
          description: Estimate code provided from the buyer. Packages client, product and estimate codes together.
          type: string

    broadcastDate:
      description: Combines the Broadcast Date & Time Information
      properties:
        broadcastDate: # TODO listed as conditional in spreadsheet, what does conditional mean?
          description: The broadcast date on which the unit aired/scheduled; UTC Standard; Receiver of data will be responsible to convert based on station's broadcast start of day
          type: string
          format: date-time 
        broadcastTime: # TODO listed as conditional in spreadsheet, what does conditional mean?
          description: The broadcast local time on which the unit aired/scheduled; UTC Standard; Receiver of data will be responsible to convert based on station's broadcast start of day
          type: string  #TODO should this be an enum?
        broadcastTimeOffset:  #TODO: Consider local time offsets. Conversion of UTC will become difficult as each receiver will need to maintain a potentially volitile dataset of stations/channels/starttimes and there is no facility/api to provide this yet. 
          description: Offset in miliseconds from local time midnight
          type: integer

    timeFrame: 
      description: Combines multiple non-contiguous start and end times 
      properties:
        startTime:
          description: Valid start time for units
          type: string
          format: date-time 
        endTime: 
          description: Valid end time for units 
          type: string
          format: date-time 

    Contact: #TODO fixed casing 
      description: Combines contact Information
      required:
        - contactType
        - referenceSourceName
      properties:
        contactType: # TODO type is a reserved word, changed to contactType
          description: Type of Contact
          type: string
          enum: [Account Executive, Sales Planner, Sales Assistant, Buyer, Billing, Creative, Delivery Service]
        referenceSourceName: 
          description: Name associated with the organization that is supplying the contact information
          type: string
        referenceSourceId: 
          description: ID associated with the organization
          type: string
        contactFirstName: 
          description: Contact First Name
          type: string
        contactLastName: 
          description: Contact Last Name
          type: string
        PhoneNumber: 
          description: Primary telephone number
          type: string
        email: 
          description: Primary email 
          type: string
        effectiveDate: 
          description: Effective date for contact
          type: string
          format: date-time
    remittanceInfo:
      description: remmittance contact information
      properties:
        referenceSourceId:
          type: string
        referenceName:
          type: string
        contactFirstName:
          type: string
        contactLastName:
          type: string
        addressLine1:
          type: string
        addressline2:
          type: string
        City:
          type: string
        State:
          type: string
        postalCode:
          type: string
        Country:
          type: string
        PhoneNumber:
          type: string
        email:
          type: string
          format: email
        Instructions:
          type: string
    Error:
      required:
        - errorCode
        - errorMessage
      properties:
        errorCode:
          type: integer
          format: int32
        errorMessage:
          type: string

    acceptedResponse:
        required:
          - transactionId
          - timeStamp
        properties:
          transactionId:
            type: string
          timeStamp:
            type: string
            format: date-time
