openapi: 3.0.0
info:
  version: 4.2.0
  title: Common Schemas
  description: Common Schemas, based on TIP 4.0 documentation
  termsOfService: http://placeholderdomain.io/terms/
  contact:
    name: TIP Initiative
    email: tipinitiative@frontrowadvisory.com
    url: http://placeholderdomain.io
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
paths: {}
components:
  schemas:
    TransactionHeader:
      properties:
        tipVersion:
          description: TIP version of the interface
          type: string
        transactionNum:
          description: Buyer or Seller generated unique number for transaction
          type: integer
        transactionType:
          description: Indicates the type of transaction (New, Changed, Cancelled)
          type: string
          enum:
            - New
            - Changed
            - Cancelled
        sourceId:
          description: Indicates the source "trading partner" unique identification
          type: string
        sourceName:
          description: Indicates the source "trading partner" name
          type: string
        timeStamp:
          description: Date and time the transaction was created
          type: string
          format: date
      required:
        - tipVersion
        - transactionNum
        - transactionType
        - sourceId
        - sourceName
        - timeStamp
    MediaOutlet:
      properties:
        mediaOutletId:
          description: Unique persistent identifier for the station or network
          type: string
        mediaOutletName:
          description: Station, network name or entity associated to mediaOutletId
          type: string
        mediaOutletType:
          description: Type of media outlet
          type: string
          enum:
            - Broadcast TV
            - OTT
            - Connected TV
            - Addressable TV
            - Digital Video
            - Mobile Video
            - Terrestrial Radio
            - Digital Audio
        mediaOutletChannel:
          description: Station or network station identification (Channel)
          type: string
        mediaOutletMarketName:
          description: Station market Name
          type: string
        mediaOutletReference:
          description: External mediaoutlet reference information
          type: string
      required:
        - mediaOutletId
        - mediaOutletName
        - mediaOutletType
    Advertiser:
      properties:
        advertiserId:
          description: Unique persistent identifier for the advertiser/client
          type: string
        advertiserName:
          description: Advertiser name
          type: string
        advertiserReference:
          description: External advertiser reference information
          type: string
      required:
        - advertiserId
        - advertiserName
    Brand:
      properties:
        brandId:
          description: Unique persistent identifier for the brand
          type: string
        brandName:
          description: Brand Name
          type: string
        brandReference:
          description: External brand reference information
          type: string
      required:
        - brandId
        - brandName
    Buyer:
      properties:
        buyerId:
          description: >-
            Unique persistent identifier for the Buying organization or trafficking agency and /or the
            supplier of the media
          type: string
        buyerName:
          description: Buying organization name and location
          type: string
        buyerReference:
          description: External buyer location reference information
          type: string
      required:
        - buyerId
        - buyerName
    Product:
      properties:
        productId:
          description: Unique persistent identifier for the product
          type: string
        productName:
          description: Product name
          type: string
        productReference:
          description: External product reference
          type: string
      required:
        - productId
        - productName
    AudienceSegment:
      properties:
        audienceSegmentId:
          description: Unique persistent identifier for audience segment
          type: string
        audienceSegmentName:
          description: Audience Segment Name
          type: string
        audienceSegmentReference:
          description: External audience segment reference
          type: string
        primaryIndicator:
          description: True/False
          type: boolean
        guarantee:
          description: True/False
          type: boolean
        ratingSource:
          description: Audience source for audience segment
          type: string
          enum:
            - Nielsen
            - ComScore
            - Internal
            - Client
        ratingStream:
          description: Type of rating stream associated to the rating source
          type: string
          enum:
            - Program Live
            - Commercial Ratings Live
            - Commercial Rating Live+3
            - Commercial Rating Live+7
      required:
        - audienceSegmentId
        - audienceSegmentName
    AudiencePricingMetric:
      properties:
        audienceMetric:
          description: Type of audience metrics (AND)
          type: string
          enum:
            - Impressions
            - Rating
            - GRPs VPVH
            - Composition
            - Reach
            - Frequency Threshold
            - Scarcity
        audienceMetricValue:
          description: audienceMetric value
          type: string
        pricingMetric:
          description: List of pricing metric segments (AND)
          type: string
          enum:
            - CPM
            - CPP
            - CPE
            - CPA
        pricingMetricValue:
          description: Audience metric dollar value
          type: number
          format: float
      required:
        - pricingMetric
        - pricingMetricValue
    Universe:
      properties:
        universeType:
          description: Universe Type (AND)
          type: string
          enum:
            - Market
            - Total US
            - Coverage
            - Addressable
        universeTypeValue:
          description: Universe type value
          type: integer
    CancellationTerms:
      properties:
        cancellationType:
          description: Type of Cancellation elements
          type: string
          enum:
            - Quarterly
            - Broadcast Date
        cancellation:
          description: Quarter name or broadcast date dependent on cancellation type
          oneOf:
            - type: string
            - type: string
              format: date-time
        cancellationPriorDays:
          description: Number of days notice needed prior to start quarter or broadcast date to request
            cancellation
          type: integer
        cancellationPercentage:
          description: Percentage of dollars allowed to be cancelled for cancellation defined
          type: number
          format: float
    TimeSeparation:
      properties:
        unitLength:
          description: Unit length
          type: integer
        timeSeparation:
          description: >-
            Agreement whereby the seller agrees to separate advertiser’s commercials by a specific length
            of time in addition to agreeing to not run another product that is directly competitive within
            a specific time frame; agreement may defined by unit length or across all lengths
          type: integer
    ReferenceId:
      properties:
        referenceSourceName:
          description: Name associated with the organization that is supplying the ids and version information
          type: string
        referenceSourceId:
          description: ID associated with the organization sending the information
          type: string
        referenceSourceLookup:
          description: Reference Source Look up; this could be URI to lookup information about the reference
            source name
          type: string
        referenceType:
          description: The type of reference IDs that are being supplied
          type: string
          enum:
            - RFP
            - Proposal
            - Deal
            - Order
            - Invoice
        referenceId:
          description: Number or ID associated with reference type(s)
          oneOf:
            - type: number
            - type: string
        referenceVersionId:
          description: Version Number to indicate what version of the reference id
          type: string
        referenceName:
          description: Free form name used to identify the type of entity such as Order Name, RFP Name
          type: string
      required:
        - referenceSourceName
        - referenceSourceId
        - referenceType
        - referenceId
    CpeCode:
      properties:
        clientCode:
          description: Client code provided from the buyer. Packages client, product and estimate codes
            together.
          type: string
        productCode:
          description: Product code provided from the buyer. Packages client, product and estimate codes
            together.
          type: string
        estimateCode:
          description: Estimate code provided from the buyer. Packages client, product and estimate codes
            together.
          type: string
    GuideLine:
      properties:
        guideLineType:
          description: Type of guideline
          type: string
          enum:
            - Content
            - Program
            - MPAA Rating
            - Site Category
            - Genre
            - Video Group
            - Video Site
        excludeOrInclude:
          type: string
          enum:
            - Include
            - Exclude
        guideLineID:
          description: Guideline identifier
          type: string
        guideLineName:
          description: Guideline Name
          type: string
      required:
        - guideLineType
        - excludeOrInclude
    BroadcastDate:
      properties:
        broadcastDate:
          description: >-
            The broadcast date on which the unit aired/scheduled; Receiver of data will be responsible
            to convert based on station's broadcast start of day; format YYYY-MM-DD; In a future release
            the broadcast date will be modified to support UTC Standard
          type: string
          format: date
        broadcastTime:
          description: >-
            The broadcast local time on which the unit aired/scheduled; UTC Standard; Receiver of data
            will be responsible to convert based on station's broadcast start of day, "Currently using
            the following: format HH:MM:SS; In a future release the broadcast time will be modified t
            support UTC Standard
          type: string
    DateWindow:
      properties:
        startDate:
          type: string
          format: date
        endDate:
          type: string
          format: date
    TimeWindow:
      properties:
        startTime:
          description: Valid start time
          type: string
          format: date-time
        endTime:
          description: Valid end time
          type: string
          format: date-time
    Contact:
      properties:
        contactType:
          description: Type of Contact
          type: string
          enum:
            - Account Executive
            - Planner
            - Assistant
            - Buyer
            - Payee
            - Creative
            - Delivery Service
        referenceSourceName:
          description: Name associated with the organization that is supplying the contact information
          type: string
        referenceSourceId:
          description: ID associated with the organization
          type: string
        contactFirstName:
          description: Contact First Name
          type: string
        contactLastName:
          description: Contact Last Name
          type: string
        addressLine1:
          description: Contact Address Line 1
          type: string
        addressLine2:
          description: Contact Address Line 2
          type: string
        city:
          description: City
          type: string
        state:
          description: State
          type: string
        postalCode:
          description: Postal Code
          type: string
        country:
          description: Country
          type: string
        phoneNumber:
          description: Primary telephone number
          type: string
        email:
          description: Primary email
          type: string
          format: email
        effectiveDate:
          description: Effective date for contact
          type: string
          format: date
      required:
        - contactType
        - referenceSourceName
        - referenceSourceId
        - contactFirstName
        - contactLastName
        - effectiveDate
    RemittanceInfo:
      properties:
        referenceSourceId:
          description: ID associated with the remittance
          type: string
        referenceName:
          description: Name associated with the remittance
          type: string
        contactFirstName:
          description: Contact First Name (not necessary)
          type: string
        contactLastName:
          description: Contact Last Name (not necessary)
          type: string
        addressLine1:
          description: Contact Address Line 1
          type: string
        addressLine2:
          description: Contact Address Line 2
          type: string
        city:
          description: City
          type: string
        state:
          description: State
          type: string
        postalCode:
          description: Postal Code
          type: string
        country:
          description: Country
          type: string
        phoneNumber:
          description: Primary telephone number
          type: string
        contactEmail:
          description: Primary email for payment remittance information
          type: string
          format: email
        portalInformation:
          description: Portal information including payment instructions
          type: string
        paymentLink:
          description: URL that directs buyer to invoice payment options
          type: string
        comments:
          description: Comments
          type: string
    DowObject:
      properties:
        Monday:
          type: boolean
        Tuesday:
          type: boolean
        Wednesday:
          type: boolean
        Thursday:
          type: boolean
        Friday:
          type: boolean
        Saturday:
          type: boolean
        Sunday:
          type: boolean
    DowEnum:
      type: string
      enum: [Monday, Tuesday, Wednesday, Thursday, Friday, Saturday, Sunday]
    DowArray:
      type: array
      items:
        $ref: '#/components/schemas/DowEnum'
      uniqueItems: true
      minItems: 1
      maxItems: 7
    SalesElement:
      properties:
        mediaOutlet:
          $ref: '#/components/schemas/MediaOutlet'
        salesElementName:
          description: Seller's sales element name; this could be either a program or daypart name
          type: string
        salesElementID:
          description: Seller's sales element ID
          type: string
        salesElementDescription:
          description: Seller's sales element description
          type: string
        salesElementType:
          description: >-
            The type of Sales Element. Time-specific would be based on start and end time other than
            a specific program. Orbit would be rotator across non-adjacent programs in a day.
          type: string
          enum:
            - Time-specific
            - Program
            - Orbit
            - Package
        programDetails:
          description: >-
            List of programs in the salesElement if there are one or multiple. For example programs in
            a Package or Orbit.
          type: string
        airingDateWindows:
          $ref: '#/components/schemas/DateWindow'
        airingTimeWindows:
          type: array
          items:
            $ref: '#/components/schemas/TimeWindow'
        hiatusDateWindows:
          type: array
          items:
            $ref: '#/components/schemas/DateWindow'
        guideLines:
          type: array
          items:
            $ref: '#/components/schemas/GuideLine'
        salesElementInventory:
          type: array
          items:
            $ref: '#/components/schemas/SalesElementInventory'
      required:
        - mediaOutlet
        - salesElementName
        - salesElementID
        - salesElementType
        - airingDateWindows
        - salesElementInventory
    SalesElementInventory:
      properties:
        calendarType:
          description: Differentiates between OTT using Calendar and Linear using Broadcast Calendar.
          type: string
          enum:
            - Broadcast
            - Calendar
        availDateWindow:
          $ref: '#/components/schemas/DateWindow'
        dow:
          type: string
          enum:
            - Monday
            - Tuesday
            - Wednesday
            - Thursday
            - Friday
            - Saturday
            - Sunday
            - Unrestricted
        inventoryType:
          type: string
          enum:
            - Commercial
            - Interstitial
            - Billboard
        linkType:
          description: Linked Unit Type
          type: string
          enum:
            - Billboard
            - Piggyback
            - Bookend
            - Sponsorship
            - Package
        inventoryPosition:
          type: string
          enum:
            - First
            - Middle
            - Last
            - Pre-Roll
            - Mid-Roll
            - Post-Roll
        inventoryLength:
          description: length of unit
          type: integer
        inventoryCapacity:
          description: Inventory Capacity
          type: integer
        inventoryAvails:
          description: Inventory Avails
          type: integer
        rate:
          type: integer
        audiences:
          type: array
          items:
            $ref: '#/components/schemas/SalesElementAudience'
      required:
        - inventoryType
        - rate
    SalesElementAudience:
      properties:
        audienceSegment:
          $ref: '#/components/schemas/AudienceSegment'
        audiencePricingMetrics:
          type: array
          items:
            $ref: '#/components/schemas/AudiencePricingMetric'
        universe:
          type: array
          items:
            $ref: '#/components/schemas/Universe'
      required:
        - audienceSegment
        - audiencePricingMetrics
        - universe
    Error:
      properties:
        errorCode:
          type: integer
        errorMessage:
          type: string
      required:
        - errorCode
        - errorMessage
    AcceptedResponse:
      properties:
        transactionId:
          type: string
        timeStamp:
          type: string
          format: date-time
      required:
        - transactionId
        - timeStamp
