openapi: 3.0.0
info:
  version: 5.1.0
  title: Inventory Avails Schemas
  description: Inventory Avails Schemas
  termsOfService: http://placeholderdomain.io/terms/
  contact:
    name: TIP Initiative
    email: tipinitiative@frontrowadvisory.com
    url: http://placeholderdomain.io
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
paths: {}
components:
  schemas:
    BuyerInventoryAvails:
      description: |
        The BuyerInventoryAvails Schema allows the buyer to formulate a query
        for Inventory meeting the listed conditions
      properties:
        transactionHeader:
          $ref: 'commonSchemas.yaml#/components/schemas/TransactionHeader'
        dateSubmitted:
          description: Buyer Submit Date for Inventory Request
          type: string
          format: date
        dueDate:
          description: Due Date for seller to respond with Inventory Information
          type: string
          format: date
        mediaOutlets:
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/MediaOutlet'
          minItems: 1
        buyer:
          $ref: 'commonSchemas.yaml#/components/schemas/Buyer'
        advertiser:
          $ref: 'commonSchemas.yaml#/components/schemas/Advertiser'
        contacts:
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/Contact'
        timePeriods:
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/TimePeriod'
          minItems: 1
        guidelines:
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/Guideline'
        political:
          description: Indicates if the request is for political pricing
          type: boolean
        inventoryTypes:
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/InventoryType'
        maxRate:
          description: Max rate spend across all inventory types
          type: number
          format: float
          minimum: 0
        currency:
          $ref: 'commonSchemas.yaml#/components/schemas/Currency'
        externalComment:
          description: Free form text to accommodate transaction comments and/or activities outside the
            TIP flow
          type: string
        audienceSegments:
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/AudienceSegment'
          minItems: 1
        pricingMetricOptions:
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/PricingMetricOption'
      required:
        - transactionHeader
        - dateSubmitted
        - mediaOutlets
        - timePeriods
        - political
        - audienceSegments
    SellerInventoryAvails:
      description: >-
        The SellerInventoryAvails Schemas defines:
        - the Seller response to previously solicited InventoryAvails request from the buyer, 
        - or Unslocited provide the buyer with the catalog of selling products, 
          and optionally provide pricing and audience information
      properties:
        transactionHeader:
          $ref: 'commonSchemas.yaml#/components/schemas/TransactionHeader'
        dateSubmitted:
          description: Submission date for the inventory
          type: string
          format: date
        buyer:
          $ref: 'commonSchemas.yaml#/components/schemas/Buyer'
        advertiser:
          $ref: 'commonSchemas.yaml#/components/schemas/Advertiser'
        contacts:
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/Contact'
          minItems: 1
        rateCard:
          $ref: 'commonSchemas.yaml#/components/schemas/RateCard'
        currency:
          $ref: 'commonSchemas.yaml#/components/schemas/Currency'
        political:
          description: Indicates that pricing being supplied are for political
          type: boolean
        mediaOutlets:
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/MediaOutlet'
          minItems: 1
        audienceSegments:
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/AudienceSegmentDetail'
          nullable: true
        availWindow:
          $ref: 'commonSchemas.yaml#/components/schemas/DateWindow'
        salesElements:
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/SalesElement'
          minItems: 1
      required:
        - transactionHeader
        - dateSubmitted
        - political
        - mediaOutlets
        - availWindow
        - salesElements
