openapi: "3.0.0"
info:
  title: Invoice Schema
  version: 4.0.0.0
  description: Invoice Schema, Based on TIP 4.0.0 Working Draft
  termsOfService: http://placeholderdomain.io/terms/,
  contact: 
    name: MIT
    email: tip-mailing-list@tbd.com
    url: http://placeholderdomain.io
  license: 
    name: MIT
    url: https://opensource.org/licenses/MIT
paths: {} 
components: 
  schemas: 
    invoiceObject: 
      required: 
      - transactionHeader
      - referenceId
      - invoiceDate
      - invoiceRevisionDate
      - calendarType
      - billingCycle
      - startDate
      - endDate
      - buyerLocation
      - advertiser
      - buylineCashTrade
      - grossAmount
      - commision
      - totalNetDollars
      - unitType
      - remittanceInfo
      properties:
        transactionHeader: 
          $ref: 'commonSchemas.yaml#/components/schemas/transactionHeader'
        referenceId:
          description: Information grouping all reference ids and their source that are associated to the proposal
          $ref: 'commonSchemas.yaml#/components/schemas/referenceIds'
        invoiceDate:
          description: Date in which the original invoice was generated
          type: string
          format: date
        invoiceRevisionDate:
          description: Required for Invoice Revision – Date in which the invoice revision was generated
          type: string
          format: date
        Month:
          description: Broadcast month in which the unuts aired
          type: string
        calenderType:
          description: The invoice calendar type
          type: string
          enum: [Broadcast, Calendar]
        billingCycle:
          description: The nvoice billing cycle
          type: string
          enum: [Monthy, Weekly]
        billingGranularity:
          description: The invoice billing granilarity
          type: string
          enum: [Order, Brand, Insertion Order, Custom]
        dueDate:
          description: Date in which payment is due on invoice
          type: string
          format: date
        startDate:
          description: First broadcast date valid for the invoice period
          type: string
          format: date
        endDate:
          description: Last broadcast date valid for the invoice period
          type: string
          format: date
        businessType:
          description: Seller-defined type of business
          type: string
        buyerLocation:
          $ref: 'commonSchemas.yaml#/components/schemas/buyerLocation'
        localNational:
          type: string
          enum: [Local, National]
        Advertiser:
          $ref: 'commonSchemas.yaml#/components/schemas/Advertiser'
        contact:
          $ref: 'commonSchemas.yaml#/components/schemas/Contact'
        buylineCashTrade:
          description: Revenue Type associated to the order
          type: string
          enum: [Cash, Barter, Trade]
        grossAmount:
          description: Total gross dollar for the invoice
          type: number
          format: float
        commision:
          description: Seller commission dollars
          type: number
          format: float
        salesTax:
          description: Sales Tax in USD applied to any elements on the invoice
          type: number
          format: float
        totalNetDollars:
          description: Total net dollars for all units with the invoice (grossamount - commission)
          type: number
        unitType:
          description: Type of invoice units
          type: string
          enum: [Units, Impressions]
        totalUnits:
          description: Total number of raw (equivalized) units (based on invoice's unit type) within the start and end date
          type: number
        remittanceInfo:
          description: refer to remittance object for data property details  #TO DO
          type: string
        externalComment:
          description: free form text to accomodate transaction
          type: string
        Line Details:
          description: Line details array of lines
          type: array
          items:
            type: object
            required:
              - buyLineIDReference
              - mediaType
              - mediaOutlet
              - productCategory
              - sellingTitle
              - lineStartDate
              - LineEndDate
              - Length
            properties:
              buyLineIDReference:
                description: Seller's Line information (add buyer identifier make optional) 
                type: string
              buyLineIDName:
                description:  Name associated to the line
                type: string
              mediaType:
                description: Type of media associated to the line
                type: string
                enum: [Linear Television, OTT, Digital, Linear Addressable, Custom]
              mediaOutlet:
                $ref: 'commonSchemas.yaml#/components/schemas/mediaOutlet'
              Brand:
                $ref: 'commonSchemas.yaml#/components/schemas/Brand'
              productCategory:
                description: ProductCategory Information associated with creative material/brand
                type: string # TO DO
              sellingTitle:
                description: Selling Title Name
                type: string
              Program:
                description: Program Name
                type: string
              cpeCode:
                #description: Client Code, Product Code & Estimate Code associated to the unit
                $ref: 'commonSchemas.yaml#/components/schemas/cpeCode'
              timeFrame:
                $ref: 'commonSchemas.yaml#/components/schemas/timeFrame'
              billableRevenue:
                description: Rate's Billable revenue type
                type: string
                enum: [Booked, Actuals, Custom]
              Rate:
                type: number
                format: float
              lineStartDate:
                description: start date of line
                type: string
                format: startDate
              LineEndDate:
                description: end date of line
                type: string
                format: date
              inventoryType:
                description: Inventory Type associated to unit  (Further Define in order to support cross 
                type: string
                enum: [Commercial, Interstitial, Billboard, Piggyback, Custom]
              Length:
                description: Length of commercial unit
                type: integer
        UnitDetails:
          description: Array of unit details
          type: array
          items:
            type: object
            oneOf:
              - $ref: '#/components/schemas/Units'
              - $ref: '#/components/schemas/Impressions'
        mediaOutletDetails:
          description: Child unit details for footprint unit to support Audience
          type: array
          items:
            type: object
            properties:
              ParentUnitId:
                type: string
              unitId:
                type: string
              mediaOutlet:
                type: object
              Rate:
                type: number
                format: float
              alternateID:
                type: string
              Preempt:
                type: boolean
              Makegood: 
                type: boolean
              ADU:
                type: boolean
              Credit:
                type: boolean
              broadcastDate:
                $ref: 'commonSchemas.yaml#/components/schemas/broadcastDate'
    unitCommonFields:
      type: object
      discriminator:
        propertyName: unitType
      required:
      - unitType
      properties:
        unitType:
          type: string
        alternateID:
          type: string
        podPosition:
          type: string
          enum: [A, Z, Custom]
        Preempt:
          type: boolean
        Makegood: 
          type: boolean
        ADU:
          type: boolean
        Credit:
          type: boolean
        Bonus:
          type: boolean
        Rate:
          type: number
          format: float
        adjustmentReason:
          type: string
        Comment:
          type: string   
    Units: 
      allOf:
      - type: object
        required:
        - broadcastDate
        properties:   
          broadcastDate:
            $ref: 'commonSchemas.yaml#/components/schemas/broadcastDate'
      - $ref: '#/components/schemas/unitCommonFields'
    Impressions:
      allOf:
      - $ref: '#/components/schemas/unitCommonFields'                             
