openapi: 3.0.0
info:
  version: 5.1.0
  title: Invoice Schema
  description: Invoice Schema
  termsOfService: http://placeholderdomain.io/terms/
  contact:
    name: TIP Initiative
    email: tipinitiative@frontrowadvisory.com
    url: http://placeholderdomain.io
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
paths: {}
components:
  schemas:
    SellerInvoices:
      description: Top level element for Invoice Seller POST operations
      properties:
        transactionHeader:
          $ref: 'commonSchemas.yaml#/components/schemas/TransactionHeader'
        referenceIds:
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/ReferenceId'
        invoiceDate:
          description: Date in which the original invoice was generated
          type: string
          format: date
        invoiceRevisionDate:
          description: Required for Invoice Revision – Date in which the invoice revision was generated
          type: string
          format: date
        billingOption:
          $ref: 'commonSchemas.yaml#/components/schemas/BillingOption'
        dueDate:
          description: Date in which payment is due on invoice
          type: string
          format: date
        dateWindow:
          $ref: 'commonSchemas.yaml#/components/schemas/DateWindow'
        businessType:
          description: Seller-defined type of business
          type: string
        buyer:
          $ref: 'commonSchemas.yaml#/components/schemas/Buyer'
        localNational:
          description: Local or National marketplace
          type: string
          enum:
            - Local
            - National
        advertiser:
          $ref: 'commonSchemas.yaml#/components/schemas/Advertiser'
        contacts:
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/Contact'
        buylineCashTrade:
          description: Revenue Type associated to the invoice
          type: string
          enum:
            - Cash
            - Barter
            - Trade
        grossAmount:
          description: Totals gross amount for the invoice
          type: number
          format: float
        commission:
          description: Invoice total commission amount
          type: number
          format: float
        salesTax:
          description: Total sales tax applied to any elements on the invoice depending on state of invoice
            origin
          type: number
          format: float
        netAmount:
          description: >-
            Total net amount for all units within the invoice start and end date (gross amount– commission
            amount + sales tax)
          type: number
          format: float
        currency:
          $ref: 'commonSchemas.yaml#/components/schemas/Currency'
        remittanceInfo:
          $ref: 'commonSchemas.yaml#/components/schemas/RemittanceInfo'
        externalComment:
          description: Free form text for comments
          type: string
        lineDetails:
          type: array
          items:
            $ref: '#/components/schemas/LineDetail'
      required:
        - transactionHeader
        - referenceIds
        - invoiceDate
        - dateWindow
        - buyer
        - advertiser
        - buylineCashTrade
        - grossAmount
        - commission
        - netAmount
        - remittanceInfo
        - lineDetails
    LineDetail:
      description: Line Detail Information
      properties:
        buyLineIdReference:
          description: Seller's Line information
          type: string
        buyLineIdName:
          description: Buyer's line information associated to seller's line
          type: string
        unitType:
          description: The type of units on the line
          type: string
          enum:
            - Units
            - Impressions
            - Non Airtime
        brand:
          $ref: 'commonSchemas.yaml#/components/schemas/Brand'
        product:
          $ref: 'commonSchemas.yaml#/components/schemas/Product'
        salesElement:
          $ref: 'commonSchemas.yaml#/components/schemas/SalesElementHeader'
        timePeriod:
          $ref: 'commonSchemas.yaml#/components/schemas/TimePeriod'
        length:
          description: Length of commercial unit
          type: integer
        cpeCode:
          $ref: 'commonSchemas.yaml#/components/schemas/CpeCode'
        billableRevenue:
          description: Indicates if the line's rate is based on booked rates or actuals (earned) rates
          type: string
          enum:
            - Booked
            - Actuals
        rate:
          type: number
          format: float
          minimum: 0
        inventoryType:
          $ref: 'commonSchemas.yaml#/components/schemas/InventoryType'
        audiencePricingMetric:
          $ref: 'commonSchemas.yaml#/components/schemas/AudiencePricingMetric'
        totalUnits:
          description: >-
            Total number of raw (equivalized) units (based on line's unit type) within the line's start
            and end date or if audience buy the total number of Raw Impressions
          type: integer
          format: int64
        unitDetails:
          type: array
          items:
            $ref: '#/components/schemas/UnitDetail'
      required:
        - buyLineIdReference
        - unitType
        - product
        - salesElement
        - length
    UnitDetail:
      description: Unit details information (required for "unit" type only)
      properties:
        unitId:
          description: Seller generated unique number - Required when unit type is equal to units
          type: string
        adId:
          description: Ad-ID
          type: string
        dateTime:
          $ref: 'commonSchemas.yaml#/components/schemas/DateTime'
        podPosition:
          $ref: 'commonSchemas.yaml#/components/schemas/InventoryPosition'
        linkType:
          $ref: 'commonSchemas.yaml#/components/schemas/LinkType'
        preempt:
          description: True/False
          type: boolean
        makegood:
          description: True/False
          type: boolean
        adu:
          description: True/False
          type: boolean
        bonus:
          description: True/False
          type: boolean
        rate:
          description: Contracted rate associated to the unit
          type: number
          format: float
        credit:
          description: True/False
          type: boolean
        adjustmentReason:
          description: >-
            Only valid on invoice revisions – reason for change of unit (e.g. rate adjustment, incorrect
            copy, etc.)
          type: string
        comment:
          description: Overall comment for the unit
          type: string
        childUnits:
          type: array
          items:
            $ref: '#/components/schemas/ChildUnitDetail'
      required:
        - unitId
    ChildUnitDetail:
      description: >-
        Child unit details for parent unit to support Mirror, Audience Network, Diginet or other forms
        of "child" units
      properties:
        unitId:
          description: Unique identifier for "child" unit
          type: string
        mediaOutlet:
          $ref: 'commonSchemas.yaml#/components/schemas/MediaOutlet'
        rate:
          description: Unit rate associated to the "child" unit
          type: number
          format: float
        adId:
          description: Ad-ID assigned to "child" unit
          type: string
        preempt:
          type: boolean
        makegood:
          type: boolean
        adu:
          type: boolean
        credit:
          type: boolean
        adjustmentReason:
          description: >-
            Only valid on invoice revisions – details reasons for change to the unit (e.g. rate adjustment,
            incorrect copy, etc.)
          type: string
        dateTime:
          $ref: 'commonSchemas.yaml#/components/schemas/DateTime'
