openapi: 3.0.0
info:
  version: 6.0.0
  title: Invoice Schemas
  description: Invoice Schemas
  termsOfService: http://placeholderdomain.io/terms/
  contact:
    name: TIP Initiative
    email: tipinitiative@frontrowadvisory.com
    url: http://placeholderdomain.io
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
paths: {}
components:
  schemas:
    SellerInvoices:
      description: Invoice schema
      properties:
        transactionHeader:
          $ref: 'commonSchemas.yaml#/components/schemas/TransactionHeader'
        referenceIds:
          description: >-
            Array of ReferenceId objects containing the invoice id and source references; may
            also contain originating RFP, Proposal and Order id and source references
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/ReferenceId'
          minItems: 1
        invoiceDate:
          description: Original Invoice Date
          type: string
          format: date
        invoiceRevisionDate:
          description: Invoice revision Date; Required for a change transaction
          type: string
          format: date
        billingOption:
          $ref: 'commonSchemas.yaml#/components/schemas/BillingOption'
        dueDate:
          description: Payment due date
          type: string
          format: date
        dateWindow:
          $ref: 'commonSchemas.yaml#/components/schemas/DateWindow'
        businessType:
          description: Defined business type on order
          type: string
        buyer:
          $ref: 'commonSchemas.yaml#/components/schemas/Buyer'
        localNational:
          description: Indicates the order's marketplace; extended enum values are allowed
          type: string
          enum:
            - Local
            - National
        advertiser:
          $ref: 'commonSchemas.yaml#/components/schemas/Advertiser'
        contacts:
          description: Array of contact objects
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/Contact'
        revenueType:
          description: Indicates the payment term; extended enum values are allowed
          type: string
          enum:
            - Cash
            - Barter
            - Trade
        grossAmount:
          description: Total gross value amount
          type: number
          format: float
        commission:
          description: Buyer commission amount
          type: number
          format: float
        salesTaxes:
          description: Total sales tax when applicable
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/ItemDetail'
        discounts:
          description: Total discount when applicable
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/ItemDetail'
        netAmount:
          description: >-
            Total net value amount  (total grossvalue  amount– commission amount- discount +
            sales tax)
          type: number
          format: float
        currency:
          $ref: 'commonSchemas.yaml#/components/schemas/Currency'
        remittanceInfo:
          $ref: 'commonSchemas.yaml#/components/schemas/RemittanceInfo'
        mediaOutlets:
          description: Array of MediaOutlet objects being ordered
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/MediaOutlet'
        externalComment:
          description: Free form text to accommodate transaction comments and/or activities outside the TIP flow
          type: string
        lineDetails:
          description: Array of LineDetail objects
          type: array
          items:
            $ref: '#/components/schemas/LineDetail'
      required:
        - transactionHeader
        - referenceIds
        - invoiceDate
        - dateWindow
        - buyer
        - advertiser
        - revenueType
        - grossAmount
        - commission
        - netAmount
        - remittanceInfo
        - mediaOutlets
        - lineDetails
    LineDetail:
      description: Line Detail Information
      properties:
        lineNum:
          description: Supplier's generated line number/id
          type: string
        lineReference:
          description: >-
            Additional reference for the supplier's line number such as line num from an external
            system source
          type: string
        lineReferences:
          description: >-
            Array of identifier objects to identify a line id and system source; note- once the
            identifier object has been adopted the goal is to remove existing lineNum
            and lineReference
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/Identifier'
        type:
          description: Indicates the type of invoice line; A Spot type requires spot details
          type: string
          enum:
            - Spot
            - Audience
            - Flat Rate
        brand:
          $ref: 'commonSchemas.yaml#/components/schemas/Brand'
        product:
          $ref: 'commonSchemas.yaml#/components/schemas/Product'
        salesElementHeader:
          $ref: 'commonSchemas.yaml#/components/schemas/SalesElementHeader'
        inventoryType:
          description: Type of advertising such as a commercial, billboard or other forms of advertisement
          type: string
        timePeriod:
          description: >-
            Array of TimePeriod objects indicating SalesElement ordered day and time
            period constraints
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/TimePeriod'
        length:
          description: Length of commercial unit
          type: integer
        cpeCode:
          $ref: 'commonSchemas.yaml#/components/schemas/CpeCode'
        # billableCosts:
        #   description: >-
        #     Indicates if the gross and net costs are booked or earned revenues calculated from
        #     the actual impression delivery; extended enum values are allowed
        #   type: string
        #   enum:
        #     - Booked
        #     - Actuals
        pricingMetric:
          $ref: 'commonSchemas.yaml#/components/schemas/PricingMetric'
        grossCost:
          description: Gross value amount for the unit count across the date window
          type: number
          format: float
          example: 150
        netCost:
          description: Gross value amount minus any fixed advertising agency commission or compensation
          type: number
          format: float
          example: 127.5
        audienceTargets:
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/AudienceTarget'
        invoiceUnits:
          description: Number of invoice units either in linear television spots, audience impressions or other metric 
          type: number
          format: float
        deliveredTargetUnits:
          description: Number of primary audience units delivered in audience impressions or other metric 
          type: number
          format: float
        deliveredThirdPartyUnits:
          description: >-
            Number of third-party audience units delivered in audience impressions 
            or other metric to support independent outsourced companies that specialize in maintaining, 
            serving tracking and analyzing the results of online ad campaigns. 
          type: number
          format: float
        unitCount:
          description: Number of units either in linear television spots or audience impressions
          type: integer
          format: int64
          minimum: 0
        unitDetails:
          description: Array of Unit Detail associated to the line detail
          type: array
          items:
            $ref: '#/components/schemas/UnitDetail'
      required:
        - lineNum
        - type
        - product
        - salesElementHeader
        - length
        - grossCost
        - netCost
    UnitDetail:
      description: Unit details information (required for 'Spot' type)
      properties:
        unitId:
          description: Seller generated unique number for a linear television spot
          type: string
        creative:
          $ref: 'commonSchemas.yaml#/components/schemas/Creative'
        dateTime:
          $ref: 'commonSchemas.yaml#/components/schemas/DateTime'
        podPosition:
          $ref: 'commonSchemas.yaml#/components/schemas/InventoryPosition'
        linkType:
          $ref: 'commonSchemas.yaml#/components/schemas/LinkType'
        isPreempt:
          description: True/False
          type: boolean
        isMakegood:
          description: True/False
          type: boolean
        isAdu:
          description: True/False
          type: boolean
        isBonus:
          description: True/False
          type: boolean
        grossRate:
          description: the billed rate associated to the unit
          type: number
          format: float
        isCredit:
          description: True/False
          type: boolean
        adjustmentReason:
          description: >-
            Only valid on invoice revisions – reason for change of unit, example data;
            rate adjustment, incorrect copy
          type: string
        comment:
          description: Overall comment for the unit
          type: string
        childUnitDetails:
          type: array
          items:
            $ref: '#/components/schemas/ChildUnitDetail'
      required:
        - creative
    ChildUnitDetail:
      description: >-
        Child unit details for parent unit to support Mirror, Audience Network, Diginet or
        other forms of 'child' units
      properties:
        unitId:
          description: >-
            Seller generated identifier for the child spot; conditional when there is a 'parent'
            unit is sold as a footprint
          type: string
        salesElementHeader:
          $ref: 'commonSchemas.yaml#/components/schemas/SalesElementHeader'
        grossRate:
          description: Unit rate associated to the 'child' unit
          type: number
          format: float
        creative:
          description: Ad-ID assigned to 'child' unit
          $ref: 'commonSchemas.yaml#/components/schemas/Creative'
        isPreempt:
          type: boolean
        isMakegood:
          type: boolean
        isAdu:
          type: boolean
        isCredit:
          type: boolean
        adjustmentReason:
          description: >-
            Only valid on invoice revisions - reason for change of unit, example data;
            rate adjustment, incorrect copy
          type: string
        dateTime:
          $ref: 'commonSchemas.yaml#/components/schemas/DateTime'
      required:
        - salesElementHeader
        - creative
