openapi: 3.0.0
info:
  version: 1.2.0
  title: logTimes Schemas
  description: logTimes Schemas, based on TIP 4.0 documentation
  termsOfService: http://placeholderdomain.io/terms/
  contact:
    name: TIP Initiative
    email: tipinitiative@frontrowadvisory.com
    url: http://placeholderdomain.io
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
paths: {}
components:
  schemas:
    LogTimesSellerObject:
      properties:
        transactionHeader:
          $ref: 'commonSchemas.yaml#/components/schemas/TransactionHeader'
        externalComment:
          type: string
        units:
          type: array
          items:
            $ref: '#/components/schemas/Unit'
      required:
        - transactionHeader
        - units
    Unit:
      properties:
        unitId:
          description: >-
            Seller generated unique number for unit (ID will likely change if unit is moved to another
            week during recon process).
          type: string
        referenceIds:
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/ReferenceId'
        cpeCode:
          $ref: 'commonSchemas.yaml#/components/schemas/CpeCode'
        mediaOutlet:
          $ref: 'commonSchemas.yaml#/components/schemas/MediaOutlet'
        buyer:
          $ref: 'commonSchemas.yaml#/components/schemas/Buyer'
        advertiser:
          $ref: 'commonSchemas.yaml#/components/schemas/Advertiser'
        brand:
          $ref: 'commonSchemas.yaml#/components/schemas/Brand'
        product:
          $ref: 'commonSchemas.yaml#/components/schemas/Product'
        salesElement:
          description: Selling Element Name
          type: string
        program:
          description: Program Name
          type: string
        daypart:
          description: Station Daypart Name
          type: string
        inventoryType:
          description: inventory Type associated to unit (list of inventory types will be expanded in
            the future)
          type: string
          enum:
            - Commercial
            - Interstitial
            - Billboard
        linkType:
          description: Linked unit type
          type: string
          enum:
            - Billboard
            - Piggyback
            - Bookend
            - Sandwich
            - Donut
        linkNum:
          description: >-
            Linked unique number to communicate the association of two or more units that have been linked
            together; only valid when the units have a link type association
          type: string
        makegood:
          description: Indicates if the unit is a makegood
          type: boolean
        adu:
          description: Indicates if the unit is a ADU
          type: boolean
        preemptUnitIDs:
          description: >-
            Desired if unit's Makegood indicator is "Y"; "original" preempted unit(s) being resolved
            by makegood; there may be one too many preempt unit ids being resolved for one makegood
          type: array
          items:
            type: string
        bonus:
          description: Indicates if the unit is a bonus
          type: boolean
        length:
          description: The duration of the unit in seconds
          type: integer
        rate:
          description: Unit Rate
          type: number
          format: float
        adId:
          description: >-
            Advertising industry standard unique identifier for the commercial. Can be an official AD-ID
            or any other ID.
          type: string
        status:
          description: Indicates the status of the unit. Describe status terms.
          type: string
          enum:
            - Aired
            - Scheduled
            - No Run
            - Finalized
            - Invoiced
        creditInd:
          description: Indicate if the unit was issued a credit
          type: boolean
        contractInterval:
          type: string
          enum:
            - Monday
            - Tuesday
            - Wednesday
            - Thursday
            - Friday
            - Saturday
            - Sunday
        timeFrame:
          $ref: 'commonSchemas.yaml#/components/schemas/TimeWindow'
        broadcastDate:
          $ref: 'commonSchemas.yaml#/components/schemas/BroadcastDate'
        childUnits:
          type: array
          items:
            $ref: '#/components/schemas/ChildUnit'
      required:
        - unitId
        - referenceIds
        - mediaOutlet
        - advertiser
        - product
        - salesElement
        - length
        - rate
        - status
    ChildUnit:
      properties:
        unitId:
          description: Unique identifier for "child" unit; Required if unit was sold as a cluster of
            units
          type: string
        mediaOutlet:
          $ref: 'commonSchemas.yaml#/components/schemas/MediaOutlet'
        rate:
          description: Unit rate associated to the "child" unit
          type: number
          format: float
        adId:
          description: >-
            Advertising industry standard unique identifier for the commercial ; Required if child unit
            status is "Aired"
          type: string
        status:
          description: Indicates the airing status of the "child" unit
          type: string
          enum:
            - Aired
            - Scheduled
            - No Run
        reason:
          description: Reason description for No-Run status
          type: string
        broadcastDate:
          $ref: 'commonSchemas.yaml#/components/schemas/BroadcastDate'
    LogTimesResponse:
      properties:
        transactionId:
          type: string
        transactionDate:
          type: string
          format: date
