openapi: "3.0.0"
info:
  version: 1.0.0
  title: logTimes Schemas
  description: logTimes Schemas, based on TIP 4.0 documentation
  termsOfService: http://placeholderdomain.io/terms/
  contact:
    name: TIP Initiative
    email: tipinitiative@frontrowadvisory.com
    url: http://placeholderdomain.io
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

paths: {} # no paths

components:
  schemas:
    logTimesSellerObject:
        required:
          - transactionHeader
          - Units
        properties:
          transactionHeader:
            $ref: 'commonSchemas.yaml#/components/schemas/transactionHeader'
          externalComment: 
            description: Test Additional Information
            type: string
          checksum: #TODO: Consider adding checksum to specs as a validation field.
            description:  Checksum value of total dollar amount and spots.  
            type: integer
          Units:
            description: Unit detail information 
            type: array
            items:
              $ref: '#/components/schemas/Unit'
          childUnitDetails:
            description: Child unit details for footprint unit to support Audience Network, Diginet or other forms of "child" units
            type: array
            items:
              $ref: '#/components/schemas/childUnitDetails'
    Unit:
      required: # TODO define what conditional means for all the properities.
        - unitId
        - referenceIds
        - mediaOutlet
        - Advertiser
        - Product
        - sellingTitle
      properties:
        unitId:
          description: Seller generated unique number for unit
          type: string
        referenceIds:
          $ref: 'commonSchemas.yaml#/components/schemas/referenceIds'
        cpeCode: 
          $ref: 'commonSchemas.yaml#/components/schemas/cpeCode'
        mediaOutlet:
          $ref: 'commonSchemas.yaml#/components/schemas/mediaOutlet'
        Buyer:
          $ref: 'commonSchemas.yaml#/components/schemas/Buyer'
        Advertiser:
          $ref: 'commonSchemas.yaml#/components/schemas/Advertiser'
        Brand:
          $ref: 'commonSchemas.yaml#/components/schemas/Brand'
        Product:
          $ref: 'commonSchemas.yaml#/components/schemas/Product'
        sellingTitle:
          description: Selling Title Name
          type: string
        Program:
          description: Program Name
          type: string
        Daypart:
          description: Seller's Daypart Name
          type: string
          #TODO: Consider salesRegionGroup
        inventoryType:
          description: inventory Type associated to unit
          type: string
          enum: [Commercial, Interstitial, Billboard]
        linkType:
          description: Linked unit type 
          type: string
          enum: [Billboard, Piggyback, Bookend]
        linkNum:
          description: Linked unique number to communicate the association of two or more units that have been linked together; only valid when the units have a link type association
          type: integer
          format: int32 
        Makegood:
          description: Indicates if the unit is a makegood
          type: boolean
        ADU:
          description: Indicates if the unit is a ADU
          type: boolean
        preemptUnitID: # TODO what does conditional mean?
          description: Desired if unit's Makegood indicator is "Y";  "original" preempted unit(s) being resolved by makegood; there may be one too many preempt unit ids being resolved for one makegoodd
          type: array
          items:
            type: string  # TODO no type is specified in the spreadsheet, if a string are there any constraints?
        Bonus:
          description: Indicates if the unit is a bonus
          type: boolean
        Length:
          description: The duration of the unit in seconds
          type: integer
          format: int32 
        Rate:
          description: Unit Rate
          type: number
          format: float 
        AdID :
          description: Indicates if the unit is being provided at no charge to the buyer in order to make up for a shortfall in viewership - only populated on order changes
          type: string
        Status: #TODO: Consider canceled status for prelogs? Consider scheduledDate, canceledDate, or generic statusChangeDate? 
          description: Indicates the status of the unit
          type: string
          enum: [Aired, Scheduled, No Run]
        Reason:
          description: Reason description for No-Run status #TODO: Consider
          type: string
        creditInd:
          description: Indicate if the unit was issued a credit
          type: boolean
        contractInterval:  #TODO Should we consider adding flight start and end dates to provide context as well?
          description: List of valid days of week for unit airing
          type: array
          items:
            type: string
            enum: [Monday, Tuesday, Wednesday, Thursday, Friday, Saturday, Sunday]
        timeFrame:
          $ref: 'commonSchemas.yaml#/components/schemas/timeFrame'
        broadcastDate:
          $ref: 'commonSchemas.yaml#/components/schemas/broadcastDate'
  
    childUnitDetails: 
      properties:
        ParentUnitId:
          description: Seller generated unique number for national footprint unit
          type: string
        unitId:
          description: Unique identifier for child unit
          type: string
        mediaOutlet:
          $ref: 'commonSchemas.yaml#/components/schemas/mediaOutlet'
        Rate:
          description: Unit Rate
          type: number
          format: float 
        AdID :
          description: Advertising industry standard unique identifier for the commercial 
          type: string
        Status:
          description: Indicates the status of the child unit
          type: string
          enum: [Aired, Scheduled, No Run]
        Reason :
          description: Reason description for No-Run status
          type: string
        broadcastDate:
          $ref: 'commonSchemas.yaml#/components/schemas/broadcastDate'

    LogTimesResponse: # TODO stub response, needs to be defined
      description: Response data # TODO stub response, needs to be defined
      properties:
        transactionId:
          type: string
        transactionDate:
          type: string
