openapi: 3.0.0
info:
  version: 5.1.0
  title: Logtimes
  description: logTimes Schemas
  termsOfService: http://placeholderdomain.io/terms/
  contact:
    name: TIP Initiative
    email: tipinitiative@frontrowadvisory.com
    url: http://placeholderdomain.io
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
paths: {}
components:
  schemas:
    SellerLogtimes:
      description: Top level element for Logtimes Seller 
      properties:
        transactionHeader:
          $ref: 'commonSchemas.yaml#/components/schemas/TransactionHeader'
        externalComment:
          description: A string that indicates additional information the seller can send to the buyer
          type: string
        units:
          description: The units listed in the API units can be defined by the system that is creating
            the API.
          type: array
          items:
            $ref: '#/components/schemas/Unit'
      required:
        - transactionHeader
        - units
    Unit:
      description: Unit detail information
      properties:
        unitId:
          description: >-
            Seller generated unique number for unit (ID will likely change if unit is moved to another
            week during recon process).
          type: string
        referenceIds:
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/ReferenceId'
        cpeCode:
          $ref: 'commonSchemas.yaml#/components/schemas/CpeCode'
        buyer:
          $ref: 'commonSchemas.yaml#/components/schemas/Buyer'
        advertiser:
          $ref: 'commonSchemas.yaml#/components/schemas/Advertiser'
        brand:
          $ref: 'commonSchemas.yaml#/components/schemas/Brand'
        product:
          $ref: 'commonSchemas.yaml#/components/schemas/Product'
        salesElement:
          $ref: 'commonSchemas.yaml#/components/schemas/SalesElementHeader'
        program:
          description: The "as-aired" program name
          type: string
        daypart:
          description: The "as-aired" seller's daypart name
          type: string
        inventoryType:
          $ref: 'commonSchemas.yaml#/components/schemas/InventoryType'
        linkType:
          $ref: 'commonSchemas.yaml#/components/schemas/LinkType'
        makegood:
          description: Indicates if the unit is a makegood
          type: boolean
        adu:
          description: Indicates if the unit is a ADU
          type: boolean
        preemptUnitIds:
          description: >-
            Desired if unit's Makegood indicator is "Y"; "original" preempted unit(s) being resolved
            by makegood; there may be one too many preempt unit ids being resolved
          type: array
          items:
            type: string
        bonus:
          description: Indicates if the unit is a no-charge bonus
          type: boolean
        length:
          description: The duration of the unit in seconds
          type: integer
        rate:
          description: Unit Rate
          type: number
          format: float
        adId:
          description: >-
            Advertising industry standard unique identifier for the commercial. Can be an official AD-ID
            or any other ID.
          type: string
        status:
          description: Indicates the airing status of the unit
          type: string
          enum:
            - Aired
            - Scheduled
            - No Run
            - Finalized
            - Invoiced
        creditInd:
          description: Indicate if the unit was issued a credit
          type: boolean
        timePeriod:
          $ref: 'commonSchemas.yaml#/components/schemas/TimePeriod'
        dateTime:
          $ref: 'commonSchemas.yaml#/components/schemas/DateTime'
        childUnits:
          type: array
          items:
            $ref: '#/components/schemas/ChildUnit'
      required:
        - unitId
        - referenceIds
        - advertiser
        - product
        - salesElement
        - length
        - status
    ChildUnit:
      description: >-
        Child unit details for footprint unit to support Audience Network, Diginet or other forms of
        "child" units
      properties:
        unitId:
          description: Unique identifier for "child" unit; Required if unit was sold as a cluster of
            units
          type: string
        mediaOutlet:
          $ref: 'commonSchemas.yaml#/components/schemas/MediaOutlet'
        rate:
          description: Unit rate associated to the "child" unit
          type: number
          format: float
        adId:
          description: >-
            Advertising industry standard unique identifier for the commercial ; Required if child unit
            status is "Aired"
          type: string
        status:
          description: Indicates the airing status of the "child" unit
          type: string
          enum:
            - Aired
            - Scheduled
            - No Run
        reason:
          description: Reason description for No-Run status
          type: string
        dateTime:
          $ref: 'commonSchemas.yaml#/components/schemas/DateTime'