openapi: "3.0.0"

info:
  version: 1.0.0
  title: Makegoods Schemas
  description: Todo
  termsOfService: https://videa.tv/visitor/
  contact:
    name: Videa API
    email: apidocs@videa.tv
    url: https://videa.tv/
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: https://api.videa.tv

paths: {} # no paths

components:
  schemas:
    enumerateMakegoodsResponse:
      required:
        - makegoodsCollection
      description: Collection of makegoods to return 
      properties:
        makegoodsCollection:
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/encodededPayloadWrapper'

    enumerateMakegoodsQuery:
      description: Query parameters for requesting a collection of makegoods
      required:
        - CommonPayloadHeader
        - startDate
        - endDate
        - limitCount
      properties:
        CommonPayloadHeader:
          $ref: 'commonSchemas.yaml#/components/schemas/commonPayloadHeader'
        startDate:
          description: Start date of the range
          type: string
          format: date-time
        endDate:
          description: End date of the range
          type: string
          format: date-time
        limitCount: 
          description: Max number of items to return
          type: integer #TODO any constraints on this?
          format: int32

    makegoodsSubscriptionRequest:
      description: A client creates a subscription by issuing a request against the subscriptions resource. The subscription namespace is client-defined via the POST operation.
      required:
        - resource
        - notificationUrl
      properties:
        resource:
          description: Resource path to watch
          type: string
          enum: [CreateMakegoodRequest, ConfirmMakegoodNotification, CancelMakegoodRequest]
        notificationUrl:
          description: The target web hook URL
          type: string
          format: uri
        clientState:
          description: Opaque string passed back to the client on all notifications. Callers may choose to use this to provide tagging mechanisms.
          type: string