openapi: 3.0.0
info:
  version: 6.0.0
  title: Makegood Schemas
  description: Makegood Schemas
  termsOfService: http://placeholderdomain.io/terms/
  contact:
    name: TIP Initiative
    email: tipinitiative@frontrowadvisory.com
    url: http://placeholderdomain.io
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
paths: {}
components:
  schemas:
    SellerMakegoodGuidelines:
      description: Schema allows seller to request Makegood Guidelines
      properties:
        transactionHeader:
          $ref: 'commonSchemas.yaml#/components/schemas/TransactionHeader'
        dateSubmitted:
          description: Seller submit date for makegood guidelines
          type: string
          format: date
        dueDate:
          description: Due date for buyer to respond with their guidelines
          type: string
          format: date
        mediaOutlet:
          $ref: 'commonSchemas.yaml#/components/schemas/MediaOutlet'
        referenceIds:
          description: >-
            Array of ReferenceId objects containing the order id references; may also contain
            originating RFP and Proposal id references
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/ReferenceId'
        cpeCode:
          $ref: 'commonSchemas.yaml#/components/schemas/CpeCode'
        buyer:
          $ref: 'commonSchemas.yaml#/components/schemas/Buyer'
        advertiser:
          $ref: 'commonSchemas.yaml#/components/schemas/Advertiser'
        makegoodType:
          description: >-
            Type(s) of makegood guidelines being requested. The request may contain one or both
            makegood types
          type: string
          enum:
            - Resolve preemption
            - Audience Underdelivery
      required:
        - transactionHeader
        - dateSubmitted
        - buyer
        - makegoodType
    BuyerMakegoodGuidelines:
      description: >-
        Schema provides buyer's list of updated makegood guidelines to seller before and
        during a campaign
      properties:
        transactionHeader:
          $ref: 'commonSchemas.yaml#/components/schemas/TransactionHeader'
        mediaOutlet:
          $ref: 'commonSchemas.yaml#/components/schemas/MediaOutlet'
        referenceIds:
          description: >-
            Array of ReferenceId objects containing the order id references; may also contain
            originating RFP and Proposal id and source references
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/ReferenceId'
        cpeCode:
          $ref: 'commonSchemas.yaml#/components/schemas/CpeCode'
        buyer:
          $ref: 'commonSchemas.yaml#/components/schemas/Buyer'
        advertiser:
          $ref: 'commonSchemas.yaml#/components/schemas/Advertiser'
        makegoodGuidelines:
          type: array
          items:
            $ref: '#/components/schemas/MakegoodGuideline'
          minItems: 1
      required:
        - transactionHeader
        - buyer
        - makegoodGuidelines
    MakegoodGuideline:
      description: Makegood Guidelines Details
      properties:
        makegoodType:
          description: Type of Offer
          type: string
          enum:
            - Resolve preemption
            - Audience Underdelivery
        salesElementOriginal:
          $ref: 'commonSchemas.yaml#/components/schemas/SalesElementHeader'
        salesElementEquivalent:
          description: Sales Element (Programming) Acceptance Rule Elements
          type: string
          enum:
            - Same Sales Element
            - Alternate Sales Element
        makegoodTargetAudienceLimit:
          description: >-
            Percent of the total original primary audience that can be delivered as makegoods.
            This is a target goal rather than a contractual limit. For audience underdelivery
            no Audience Limit is needed.
          type: number
          format: float
        makegoodRatio:
          description: Maximum number of makegood spots allowed to resolve preempt/missed unit -
          type: integer
        makegoodWindow:
          description: Rule defined for makegood window to resolve preempt/missed unit
          type: string
          enum:
            - Original Broadcast Week
            - Original Broadcast Month
            - Within Flight Dates
        externalComment:
          description: Free form text to accommodate transaction comments and/or activities outside the TIP flow
          type: string
      required:
        - makegoodType
        - salesElementEquivalent
    SellerMakegoodOffers:
      description: >-
        Seller Makegood offer Model allows the seller to communicate the proposed changes
        to an existing and runnin ad compaign
      properties:
        transactionHeader:
          $ref: 'commonSchemas.yaml#/components/schemas/TransactionHeader'
        referenceIds:
          description: >-
            Array of ReferenceId objects containing the order id references; may also contain
            originating RFP and Proposal id references
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/ReferenceId'
        makegoodType:
          description: Type of Makegood Offer
          type: string
          enum:
            - Resolve preemption
            - Audience Underdelivery
        externalComment:
          description: Free form text to accommodate transaction comments and/or activities outside the TIP flow
          type: string
        preemptDetails:
          description: Array of preempt details; Required when makegood type is equal to Resolve Preemptions
          type: array
          items:
            $ref: '#/components/schemas/PreemptDetail'
          minItems: 0
        makegoodDetails:
          type: array
          items:
            $ref: '#/components/schemas/MakegoodOfferDetail'
          minItems: 1
      required:
        - transactionHeader
        - referenceIds
        - makegoodType
        - makegoodDetails
    PreemptDetail:
      description: Preempt details
      properties:
        preemptNum:
          type: string
        salesElement:
          $ref: 'commonSchemas.yaml#/components/schemas/SalesElementTransaction'
        preemptReason:
          description: Free form text to accommodate transaction comments and/or activities outside the TIP flow
          type: string
        makegoodNumLinks:
          description: List of makegoodNum proposed to substitute for this preempt
          type: array
          items:
            type: integer
      required:
        - preemptNum
    MakegoodOfferDetail:
      description: Packages common makegood attributes into single object
      properties:
        makegoodNum:
          description: Unique ID associated to makegood offer
          type: integer
        salesElement:
          $ref: 'commonSchemas.yaml#/components/schemas/SalesElementTransaction'
        makegoodReason:
          description: Free form text to accommodate transaction comments and/or activities outside the TIP flow
          type: string
        makegoodAssumedConfirm:
          description: >-
            Makegood is 'assumed confirmed' based on buyer-seller discussions made outside of
            framework. Booked indicates the seller has originated placement in the traffic system.
            If no action is taken the spot will air. This field indicates the urgency to take
            action.
            'Not Booked' -
            'Booked' - Spot has already been placed in traffic system
          type: string
          enum:
            - Booked
            - Not Booked
        preemptNumLinks:
          description: List of preemptNum being replaced by this makegood.
          type: array
          items:
            type: integer
      required:
        - makegoodNum
        - salesElement
    BuyerMakegoodOffers:
      description: Alias to Generic CancelConfirmRecallReject Object
      properties:
        transactionHeader:
          $ref: 'commonSchemas.yaml#/components/schemas/TransactionHeader'
        referenceIds:
          description: >-
            Array of ReferenceId objects containing the order id references; may also contain
            originating RFP and Proposal id references
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/ReferenceId'
          minItems: 1
        comments:
          description: Free form comments
          type: string
      required:
        - transactionHeader
