openapi: 3.0.0
info:
  version: 5.0.0
  title: Buyer requesting New Order or Order Change Request to Seller
  description: Buyer/Order
  termsOfService: http://placeholderdomain.io/terms/
  contact:
    name: TIP Initiative
    email: tipinitiative@frontrowadvisory.com
    url: http://placeholderdomain.io
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
paths: {}
components:
  schemas:
    BuyerOrderRequestObject:
      description: >-
        Allows the buyer to send the detailed order information for a given order; execution is a summary
        of the sales elements details, thus allowing the seller to automatically create lines based on
        individual system's rules. Buyer must submit entire order for Order Change Request using the
        last confirmed booked order version response. Seller will be responsible for deciphering change
        request from buyer. Cancellation of order either prior to start or mid flight will be submitted
        in an order change request
      properties:
        transactionHeader:
          $ref: 'commonSchemas.yaml#/components/schemas/TransactionHeader'
        referenceIds:
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/ReferenceId'
        orderBookedDate:
          description: Date in which the buyer
          type: string
          format: date
        buyer:
          $ref: 'commonSchemas.yaml#/components/schemas/Buyer'
        commission:
          description: Buyer commission percentage
          type: number
          format: float
        advertiser:
          $ref: 'commonSchemas.yaml#/components/schemas/Advertiser'
        brand:
          $ref: 'commonSchemas.yaml#/components/schemas/Brand'
        product:
          $ref: 'commonSchemas.yaml#/components/schemas/Product'
        cpeCode:
          $ref: 'commonSchemas.yaml#/components/schemas/CpeCode'
        budget:
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/Budget'
        contacts:
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/Contact'
        revenueType:
          description: How the proposal is being negotiated for payment terms
          type: string
          enum:
            - Cash
            - Barter
            - Trade
        businessType:
          description: Seller defined type of business
          type: string
        localNational:
          description: Market Type for Proposal
          type: string
          enum:
            - Local
            - National
        dealYear:
          description: The broadcast year in which the proposal is being negotiated for
          type: integer
        calendarType:
          description: The calendar in which the order was negotiated
          type: string
          enum:
            - Broadcast
            - Calendar
            - Nielsen
        billingOption:
          $ref: 'commonSchemas.yaml#/components/schemas/BillingOption'
        equivalized:
          description: Indicates if the audience values are equivalized to the unit's length
          type: boolean
        dateWindow:
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/DateWindow'
        cancellationTerms:
          $ref: 'commonSchemas.yaml#/components/schemas/CancellationTerms'
        timeSeparations:
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/TimeSeparation'
        termsOfSales:
          description: Contract terms
          type: string
        externalComment:
          description: Free form text to accommodate transaction comments and/or activities outside the
            TIP flow
          type: string
        rateCard:
          $ref: 'commonSchemas.yaml#/components/schemas/RateCard'
        currency:
          $ref: 'commonSchemas.yaml#/components/schemas/Currency'
        mediaOutlets:
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/MediaOutlet'
        audienceSegments:
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/AudienceSegmentDetail'
        salesElements:
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/SalesElementTransaction'
      required:
        - transactionHeader
        - referenceIds
        - orderBookedDate
        - buyer
        - commission
        - contacts
        - revenueType
        - businessType
        - calendarType
        - equivalized
        - dateWindow
        - mediaOutlets
    OrderConfirmResponseObject:
      description: >-
        Allows the seller to respond to an order or order change request with a confirmed booked confirmation
      properties:
        transactionHeader:
          $ref: 'commonSchemas.yaml#/components/schemas/TransactionHeader'
        referenceIds:
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/ReferenceId'
        confirmedBookedDate:
          description: Date that the Order was Confirmed Booked
          type: string
          format: date
        comments:
          description: Free form comments with "Not Accepted" Reason
          type: string
      required:
        - transactionHeader
        - referenceIds
        - confirmedBookedDate
    OrderRecall:
      description: >-
        Allows the buyer to recall a new order or order change request ; seller must respond back with
        acceptance or failure of the recall request. Note: Seller's system defined the rules for acceptance
        or failure of request
      properties:
        transactionHeader:
          $ref: 'commonSchemas.yaml#/components/schemas/TransactionHeader'
        referenceIds:
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/ReferenceId'
        recallDate:
          description: >-
            Buyer requesting to recall a previously submitted new or changed order. Seller responding
            back to Buyer acceptance or failure of request.
          type: string
          format: date
        comments:
          description: Free form comments
          type: string
      required:
        - transactionHeader
        - referenceIds
        - recallDate
    OrderReject:
      description: >-
        Allows the seller to reject a new order or order change request; seller must respond back with
        rejection comments
      properties:
        transactionHeader:
          $ref: 'commonSchemas.yaml#/components/schemas/TransactionHeader'
        referenceIds:
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/ReferenceId'
        rejectionDate:
          description: Date the order was rejected
          type: string
          format: date
        comments:
          description: Free form comments
          type: string
      required:
        - transactionHeader
        - referenceIds
        - rejectionDate
