openapi: 3.0.0
info:
  version: 5.1.0
  title: Buyer requesting New Order or Order Change Request to Seller
  description: Buyer/Order
  termsOfService: http://placeholderdomain.io/terms/
  contact:
    name: TIP Initiative
    email: tipinitiative@frontrowadvisory.com
    url: http://placeholderdomain.io
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
paths: {}
components:
  schemas:
    BuyerOrders:
      oneOf:
        - $ref: '#/components/schemas/BuyerOrdersObj'
        - $ref: 'commonSchemas.yaml#/components/schemas/CancelConfirmRecallReject'
    BuyerOrdersObj:
      description: Create or Change an Order in the Seller System
      properties:
        transactionHeader:
          $ref: 'commonSchemas.yaml#/components/schemas/TransactionHeader'
        referenceIds:
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/ReferenceId'
        orderBookedDate:
          description: Date in which the buyer
          type: string
          format: date
        buyer:
          $ref: 'commonSchemas.yaml#/components/schemas/Buyer'
        commission:
          description: Buyer commission percentage
          type: number
          format: float
        advertiser:
          $ref: 'commonSchemas.yaml#/components/schemas/Advertiser'
        brand:
          $ref: 'commonSchemas.yaml#/components/schemas/Brand'
        product:
          $ref: 'commonSchemas.yaml#/components/schemas/Product'
        budget:
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/Budget'
        cpeCode:
          $ref: 'commonSchemas.yaml#/components/schemas/CpeCode'
        contacts:
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/Contact'
        revenueType:
          description: How the proposal is being negotiated for payment terms
          type: string
          enum:
            - Cash
            - Barter
            - Trade
        businessType:
          description: Seller defined type of business
          type: string
        localNational:
          description: Market Type for Proposal
          type: string
          enum:
            - Local
            - National
        dealYear:
          description: The broadcast year in which the proposal is being negotiated for
          type: string
        calendarType:
          description: The calendar in which the order was negotiated
          type: string
          enum:
            - Broadcast
            - Calendar
            - Nielsen
        billingOption:
          $ref: 'commonSchemas.yaml#/components/schemas/BillingOption'
        equivalized:
          description: Indicates if the audience values are equivalized to the unit's length
          type: boolean
        dateWindow:
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/DateWindow'
        cancellationTerms:
          $ref: 'commonSchemas.yaml#/components/schemas/CancellationTerms'
        timeSeparations:
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/TimeSeparation'
        termsOfSales:
          description: Contract terms
          type: string
        externalComment:
          description: Free form text to accommodate transaction comments and/or activities outside the
            TIP flow
          type: string
        rateCard:
          $ref: 'commonSchemas.yaml#/components/schemas/RateCard'
        currency:
          $ref: 'commonSchemas.yaml#/components/schemas/Currency'
        mediaOutlets:
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/MediaOutlet'
        audienceSegments:
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/AudienceSegmentDetail'
        salesElements:
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/SalesElementTransaction'
      required:
        - transactionHeader
        - referenceIds
        - orderBookedDate
        - buyer
        - commission
        - contacts
        - revenueType
        - businessType
        - calendarType
        - equivalized
        - dateWindow
        - mediaOutlets
