openapi: "3.0.0"
info:
  version: 4.2.0
  title: Create a proposal to send to the buyer system
  description: Seller/Proposal Schemas, based on TIP 4.0.0 documentation
  termsOfService: http://placeholderdomain.io/terms/
  contact:
    name: TIP Initiative
    email: tipinitiative@frontrowadvisory.com
    url: http://placeholderdomain.io
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

paths: {} # no paths

components:
  schemas:
    ProposalObject:
      description: >-
        Allows the seller to respond back to the buyer with the detailed proposal
         for a given RFP or revised proposal; Multiple versions of a proposal can be 
         under negotiation for the same campaign, but only one version may be executed; 
         buyer must submit a "Proposal Change Request" for the last proposal 
         version submission; seller must respond back with a Proposal Response 
         that contains a new version number when submitting new versions.  
        New Proposals may be submitted without a RFP Response 				
      properties:
        transactionHeader:
          $ref: 'commonSchemas.yaml#/components/schemas/TransactionHeader'
        referenceIds:
          description: Information grouping all reference ids and their source that are associated to the proposal
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/ReferenceId'
          minItems: 1
        expirationDate:
          description: Date in which the proposal’s pricing and audience estimates expire
          type: string
          format: date-time
        buyer:
          $ref: 'commonSchemas.yaml#/components/schemas/Buyer'
        commission:
          description: Buyer commission percentage
          type: number  
          format: double 
        advertiser:
          $ref: 'commonSchemas.yaml#/components/schemas/Advertiser'
        brand:
          $ref: 'commonSchemas.yaml#/components/schemas/Brand'
        product:
          $ref: 'commonSchemas.yaml#/components/schemas/Product'
        cpeCode:
          $ref: 'commonSchemas.yaml#/components/schemas/CpeCode'
        contacts:
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/Contact'
        revenueType:
          description: How the proposal is being negotiated for payment terms
          type: string
          enum: 
          - Cash
          - Barter
          - Trade
        businessType:
          description: Seller-defined type of business 
          type: string
        localNational:
          description: Market Type for Proposal 
          type: string
          enum:
          - local
          - National
        dealYear:
          description: The broadcast year in which the proposal is being negotiated for
          type: integer
          format: int32
        billingOption:
          $ref: 'commonSchemas.yaml#/components/schemas/BillingOption'
        equivalized:
          description: >-
            Indicates if the impressions weighted down or up from 30-second impressions 
            based on their ratio of their length to 30 seconds.
          type: boolean
        dateWindow:
          description: An array of Date intervals
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/DateWindow'
          minItems: 1
        cancellationTerms:
          $ref: 'commonSchemas.yaml#/components/schemas/CancellationTerms'
        timeSeparation:
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/TimeSeparation'
        termsOfSales:
          description: The information specific to payment terms, preemption status, etc.
          type: string 
        externalComment:
          description: Free form text to accommodate transaction comments and/or activities outside the TIP flow
          type: string 
        rateCard:
          $ref: 'commonSchemas.yaml#/components/schemas/RateCard'
        currency:
          $ref: 'commonSchemas.yaml#/components/schemas/Currency'
        mediaOutlets:
          description: an array of mediaoutlets included in the proposal
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/MediaOutlet'
          minItems: 1
        audienceSegments:
          description: an array of Audience Segments per media outlet 
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/AudienceSegmentDetail'
        salesElements:
          description: an array of sales elements in the proposal/transaction
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/SalesElementTransaction'
      required:
        - transactionHeader
        - referenceIds
        - buyer
        - commission
        - contacts
        - revenueType
        - businessType
        - equivalized
        - dateWindow
        - mediaOutlets




