openapi: 3.0.0
info:
  version: 4.2.0
  title: RFP Schema
  description: RFP Schema, Based on TIP 4.0 Working Draft
  termsOfService: http://placeholderdomain.io/terms/
  contact:
    name: TIP Initiative
    email: tipinitiative@frontrowadvisory.com
    url: http://placeholderdomain.io
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
paths: {}
components:
  schemas:
    RFPRequestObject:
      properties:
        transactionHeader:
          $ref: 'commonSchemas.yaml#/components/schemas/TransactionHeader'
        referenceIds:
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/ReferenceId'
        dateSubmitted:
          description: Buyer Submit Date for the RFP
          type: string
          format: date
        dueDate:
          description: Due Date for the response
          type: string
          format: date
        buyer:
          $ref: 'commonSchemas.yaml#/components/schemas/Buyer'
        commission:
          description: Buyer Commission percentage amount
          type: number
          format: float
        advertiser:
          $ref: 'commonSchemas.yaml#/components/schemas/Advertiser'
        brand:
          $ref: 'commonSchemas.yaml#/components/schemas/Brand'
        product:
          $ref: 'commonSchemas.yaml#/components/schemas/Product'
        contacts:
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/Contact'
        currency:
          $ref: 'commonSchemas.yaml#/components/schemas/Currency'
        budget:
          description: Overall total budget for the RFP
          type: number
          format: float
        timePeriodPreferences:
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/TimePeriod'
          minItems: 1
        marketPreferences:
          description: List of market preferences (AND) "<Market Name>"
          type: array
          items:
            type: string
        audiencePreferences:
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/AudienceSegment'
        unitLengthPreferences:
          description: List of unit length preferences (AND) "<Unit Length>"
          type: array
          items:
            type: integer
        guidelines:
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/GuideLine'
        objective:
          description: KPI of the overall campaign
          type: string
        comments:
          description: Additional Information
          type: string
        campaignGoals:
          type: array
          items:
            $ref: '#/components/schemas/CampaignGoal'
      required:
        - transactionHeader
        - referenceIds
        - dateSubmitted
        - advertiser
        - contacts
        - timePeriodPreferences
    CampaignGoal:
      properties:
        distributionType:
          description: Goal Type Element used for distribution
          type: string
          enum:
            - MediaType
            - Daypart
            - Market
            - Quarter
            - Month
            - Week
            - AddedValue
        distributionMethod:
          description: Distribution Method Elements - Audience distributions pertain to the primary demo
            audience
          type: string
          enum:
            - Impressions
            - GRPs
            - Units
            - Budget
        distributionName:
          description: >-
            This is the name for the distribution type; for example it could be Daypart Name, or Quarter
            Name, etc.
          type: string
        distribution:
          description: This defines how the distributions for the method are being defined
          type: string
          enum:
            - Percentage
            - Exact Value
        distributionValue:
          description: >-
            This is the value for the distribution goal; it could be exact numeric value or a a percentage
            amount
          type: number
          format: float
        distributionOrder:
          description: >-
            Only populate when multiple distributions types are defined; defines the nesting order for
            the distributions
          type: integer
          minimum: 0
        distributionOrderParent:
          description: >-
            Only populate when multiple distributions types are defined; defines the parent when there
            are multiple nesting orders
          type: integer
          nullable: true
      required:
        - distributionType
        - distributionMethod
        - distributionName
        - distribution
        - distributionValue
        - distributionOrder
