openapi: "3.0.0"
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: []
info:
  version: 4.0rc1
  title: Commercial Instructions
  description: >-
    Allows the creative agency or service provider of commercial instructions to send new or
    revised traffic instructions on how commercial copy should be applied to units (No request from
    Seller is required)
  termsOfService: http://placeholderdomain.io/terms/
  contact:
    name: TIP Initiative
    email: tipinitiative@frontrowadvisory.com
    url: http://placeholderdomain.io
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: http://placeholderdomain.io
paths:
  /buyer/commercialInstructions:
    post:
      tags:
        - Buyer
      summary: Buyer Commercial Instructions POST
      description: >-
        Allows the creative agency or service provider of commercial instructions to send new or
        revised traffic instructions on how commercial copy should be applied to units (No request
        from Seller is required)
      operationId: commercialInstructionsPost
      requestBody:
        description: commercial instructions required
        required: true
        content:
          application/json:
            schema:
              $ref: 'schemas/commercialInstructionSchemas.yaml#/components/schemas/CommercialInstructionsRequestObject'
      responses:
        '200':
          description: request accepted successfully
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: 'schemas/commonSchemas.yaml#/components/schemas/Error'
