openapi: "3.0.0"

components:
 securitySchemes:
    bearerAuth: 
      type: http
      scheme: bearer
      bearerFormat: JWT 
security:
  - bearerAuth: []

info:
  version: "0.0.1"
  title: Inventory Avails
  description: Inventory Endpoints
  termsOfService: http://placeholderdomain.io/terms/
  contact:
    name: TIP Initiative
    email: tipinitiative@frontrowadvisory.com
    url: http://placeholderdomain.io
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: http://placeholderdomain.io

paths:
  /inventory/avails/buyers:
    post:
      summary: Send the request for the inventory avails required
      description: Allows the Buyer as part of campaign planning to initiate an Inventory Request to Seller
      operationId: inventoryAvailsBuyers
      requestBody:
        description: Send the request for the inventory avails required
        required: true
        content:
          application/json:
            schema:
              $ref: 'schemas/inventoryAvailsSchemas.yaml#/components/schemas/inventoryAvailsBuyerObject'
      responses:
        '200':
          description: Request processed successfully
          content:
            application/json:
              schema:
                $ref: 'schemas/inventoryAvailsSchemas.yaml#/components/schemas/inventoryAvailsResponse'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: 'schemas/commonSchemas.yaml#/components/schemas/Error'

      callbacks:
          inventoryAvailsCallback:
            '{$request.body#/callbackUrl}':
              post:
                  requestBody:   # Contents of the callback message
                    required: true
                    content:
                      application/json:
                        schema:
                          $ref: 'schemas/inventoryAvailsSchemas.yaml#/components/schemas/inventoryAvailsSellerObject'
                  responses:   # Expected responses to the callback message
                    '200':
                      description: Request processed successfully
                      content:
                        application/json:
                          schema:
                            $ref: 'schemas/inventoryAvailsSchemas.yaml#/components/schemas/inventoryAvailsResponse'
                    default:
                      description: unexpected error
                      content:
                        application/json:
                          schema:
                            $ref: 'schemas/commonSchemas.yaml#/components/schemas/Error'

  /inventory/avails/sellers:
    post:
      summary: Seller POSTs the the Inventory Avails information to the buyer's system
      description: Allows the Seller to send inventory criteria such as Stations, Selling Titles, Inventory Types, Pricing, Audience Estimates upon a manual request
      operationId: inventoryAvailsSellers
      requestBody:
        description: Seller POSTs the the Inventory Avails information to the buyer's system
        required: true
        content:
          application/json:
            schema:
              $ref: 'schemas/inventoryAvailsSchemas.yaml#/components/schemas/inventoryAvailsSellerObject'
      responses:
        '200':
          description: Request processed successfully
          content:
            application/json:
              schema:
                $ref: 'schemas/inventoryAvailsSchemas.yaml#/components/schemas/inventoryAvailsResponse'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: 'schemas/commonSchemas.yaml#/components/schemas/Error'
