openapi: "3.0.0"
components:
 securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: []
info:
  version: 6.0.0
  title: Inventory Avails
  description: Inventory Endpoints
  termsOfService: http://placeholderdomain.io/terms/
  contact:
    name: TIP Initiative
    email: tipinitiative@frontrowadvisory.com
    url: http://placeholderdomain.io
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: http://placeholderdomain.io/v6.0.0

paths:
  /buyer/inventoryAvails/subscription:
    post:
      tags:
        - Buyer
      summary: Allows the Buyer as part of campaign planning to initiate an Inventory Request to Seller
      description: >-
        This endpoint is hosted at the seller end. Allows the Buyer as part of campaign planning
        to initiate an Inventory Request to Seller.<br/>
        Supported Transaction Types:<br/>
        <lo>- New</lo>
      operationId: BuyerInventoryAvails
      requestBody:
        description: Send the request for the inventory avails required
        required: true
        content:
          application/json:
            schema:
              oneOf:
                - $ref: 'schemas/inventoryAvailsSchemas.yaml#/components/schemas/BuyerInventoryAvailsSubscription'
                - $ref: 'schemas/commonSchemas.yaml#/components/schemas/CancelConfirmRecallReject'
              xml:
                name: BuyerInventoryAvailsRequest
            examples:
              New:
                value:
                  $ref: 'examples\6.0.0\Buyer\JSON\InventoryAvailsSubscriptionNew.json'
              Change:
                value:
                  $ref: 'examples\6.0.0\Buyer\JSON\InventoryAvailsSubscriptionChange.json'
              Cancel:
                value:
                  $ref: 'examples\6.0.0\Buyer\JSON\InventoryAvailsSubscriptionCancel.json'
          application/xml:
            schema:
              oneOf:
                - $ref: 'schemas/inventoryAvailsSchemas.yaml#/components/schemas/BuyerInventoryAvailsSubscription'
                - $ref: 'schemas/commonSchemas.yaml#/components/schemas/CancelConfirmRecallReject'
              xml:
                name: BuyerInventoryAvailsRequest
            examples:
              New:
                value:
                  $ref: 'examples\6.0.0\Buyer\XML\InventoryAvailsSubscriptionNew.xml'
              Change:
                value:
                  $ref: 'examples\6.0.0\Buyer\XML\InventoryAvailsSubscriptionChange.xml'
              Cancel:
                value:
                  $ref: 'examples\6.0.0\Buyer\XML\InventoryAvailsSubscriptionCancel.xml'
      responses:
        '200': #OK - in case request can be fullfiled in realtime
          $ref: 'schemas/commonResponses.yaml#/components/responses/Success'
        '201': #Created - Request as created
          $ref: 'schemas/commonResponses.yaml#/components/responses/Created'
        '400': #Bad Request
          $ref: 'schemas/commonResponses.yaml#/components/responses/BadRequest'
        '401': #Unauthorized
          $ref: 'schemas/commonResponses.yaml#/components/responses/Unauthorized'
        '403': #Forbidden
          $ref: 'schemas/commonResponses.yaml#/components/responses/Forbidden'
        '404': #Not Found
          $ref: 'schemas/commonResponses.yaml#/components/responses/NotFound'
        '405': #Not Allowed
          $ref: 'schemas/commonResponses.yaml#/components/responses/NotAllowed'
        default: #unexpected
          $ref: 'schemas/commonResponses.yaml#/components/responses/Unexpected'
  /seller/inventoryAvails:
    post:
      tags:
        - Seller
      summary: Allows the Seller to post to the buyer their catalog of selling products, pricing and audience information
      description: >
        This endpoint will be hosted at the buyer side.
        Allows the Seller to send Available Selling inventory by station, Selling Element, Inventory Types,
        Pricing, Audience Estimates either solicited or unsolicited<br/>
        Supported Transaction Types:<br/>
        <lo>- New</lo>
      operationId: SellerInventoryAvails
      requestBody:
        description: Seller POSTs the the Inventory Avails information to the buyer's system
        required: true
        content:
          application/json:
            schema:
              $ref: 'schemas/inventoryAvailsSchemas.yaml#/components/schemas/SellerInventoryAvails'
            examples:
              New:
                value:
                  $ref: 'examples\6.0.0\Seller\JSON\InventoryAvailsNew.json'
          application/xml:
            schema:
              $ref: 'schemas/inventoryAvailsSchemas.yaml#/components/schemas/SellerInventoryAvails'
            examples:
              New:
                value:
                  $ref: 'examples\6.0.0\Seller\XML\InventoryAvailsNew.xml'
      responses:
        '200': #OK
          $ref: 'schemas/commonResponses.yaml#/components/responses/Success'
        '400': #Bad Request
          $ref: 'schemas/commonResponses.yaml#/components/responses/BadRequest'
        '401': #Unauthorized
          $ref: 'schemas/commonResponses.yaml#/components/responses/Unauthorized'
        '403': #Forbidden
          $ref: 'schemas/commonResponses.yaml#/components/responses/Forbidden'
        '404': #Not Found
          $ref: 'schemas/commonResponses.yaml#/components/responses/NotFound'
        '405': #Not Allowed
          $ref: 'schemas/commonResponses.yaml#/components/responses/NotAllowed'
        default: #unexpected
          $ref: 'schemas/commonResponses.yaml#/components/responses/Unexpected'

