openapi: "3.0.0"
components:
 securitySchemes:
    bearerAuth: 
      type: http
      scheme: bearer
      bearerFormat: JWT 
security:
  - bearerAuth: []

info:
  version: 4.0.1
  title: Invoice endpoint
  description: Allows the seller to send to the buyer both new and revised invoice information (No Request from buyer is Required)
  termsOfService: http://placeholderdomain.io/terms/
  contact:
    name: TIP Forum
    email: tip-mailing-list@tbd.com
    url: http://placeholderdomain.io
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: http://placeholderdomain.io

paths:
  /seller/invoice:
    post:
      summary: Allows the seller to send to the buyer new invoice information (No Request from buyer is Required)
      description: Allows the seller to send to the buyer new invoice information
      operationId: invoicePostSeller
      requestBody:
        description: Invoice body included in request
        required: true
        content:
          application/json:
            schema:
              $ref: 'schemas/invoiceSchemas.yaml#/components/schemas/invoiceObject'
      responses:
        '200':
          description: Request processed successfully
          content:
            application/json:
              schema:
                $ref: 'schemas/invoiceSchemas.yaml#/components/schemas/invoiceObject'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: 'schemas/commonSchemas.yaml#/components/schemas/Error'
  /seller/invoice/{invoiceId}:
    parameters:
    - name: invoiceId
      in: path
      required: true
      description: The invoice Id
      schema:
        type: string
    put:
      summary: Allows the seller to send to the buyer revised invoice information (No Request from buyer is Required)
      description: Allows the seller to send to the buyer revised invoice information
      operationId: invoicePutSeller
      requestBody:
        description: Invoice body included in request
        required: true
        content:
          application/json:
            schema:
              $ref: 'schemas/invoiceSchemas.yaml#/components/schemas/invoiceObject'
      responses:
        '200':
          description: Request processed successfully
          content:
            application/json:
              schema:
                $ref: 'schemas/invoiceSchemas.yaml#/components/schemas/invoiceObject'
        '404':
          description: Requested invoice not found  
          # TODO define response payload      
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: 'schemas/commonSchemas.yaml#/components/schemas/Error'
    delete:
      summary: Allows the seller to request the removal of previously submitted invoice
      description: Allows the seller to request the removal of previously submitted invoice
      operationId: invoiceDeleteSeller
      responses:
        '200':
          description: Request processed successfully
        '404':
          description: Invoice not found
          # TODO define response payload  
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: 'schemas/commonSchemas.yaml#/components/schemas/Error'       