openapi: "3.0.0"

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []

info:
  version: 1.2.0
  title: Invoice
  description: Allows the seller to send to the buyer both new and revised invoice information
  termsOfService: http://placeholderdomain.io/terms/
  contact:
    name: TIP Initiative
    email: tipinitiative@frontrowadvisory.com
    url: http://placeholderdomain.io
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

servers:
  - url: http://placeholderdomain.io

paths:
  /seller/invoice:
    post:
      tags:
        - Seller
      summary: Seller Invoice POST
      description: >-
        Allows the seller to send to the buyer new invoice information (No Request from buyer is
        Required)
      operationId: invoicePostSeller
      requestBody:
        description: Invoice body included in request
        required: true
        content:
          application/json:
            schema:
              $ref: 'schemas/invoiceSchemas.yaml#/components/schemas/InvoiceObject'
      responses:
        '200':
          description: Request processed successfully
          content:
            application/json:
              schema:
                $ref: 'schemas/invoiceSchemas.yaml#/components/schemas/InvoiceObject'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: 'schemas/commonSchemas.yaml#/components/schemas/Error'
