openapi: "3.0.0"

components:
 securitySchemes:
    bearerAuth: 
      type: http
      scheme: bearer
      bearerFormat: JWT 
security:
  - bearerAuth: []

info:
  version: 1.2.0
  title: logtimes
  description: Seller posts a Logtimes on the buyer's server
  termsOfService: http://placeholderdomain.io/terms/
  contact:
    name: TIP Initiative
    email: tipinitiative@frontrowadvisory.com
    url: http://placeholderdomain.io
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: http://placeholderdomain.io

paths:
  /seller/logtimes:
    post:
      tags:
        - Seller
      summary: Seller Logtimes POST
      description: >-
        Allows the seller to send to the buyer the log times information (No Request from buyer is
        Required)
      operationId: logsTimesSeller
      requestBody:
        description: seller POSTs the Log Times report to the buyer's system
        required: true
        content:
          application/json:
            schema:
              $ref: 'schemas/logTimesSchemas.yaml#/components/schemas/LogTimesSellerObject'
      responses:
        '200':
          description: Request processed successfully
          content:
            application/json:
              schema:
                $ref: 'schemas/logTimesSchemas.yaml#/components/schemas/LogTimesResponse'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: 'schemas/commonSchemas.yaml#/components/schemas/Error'
