openapi: "3.0.0"

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: []

info:
  version: 1.0.1
  title: Makegoods
  description: Makegoods
  termsOfService: http://placeholderdomain.io/terms/
  contact:
    name: TIP Forum
    email: tip-mailing-list@tbd.com
    url: http://placeholderdomain.io
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: http://placeholderdomain.io

paths:

  /v1/makegoods/create:
    post:
      summary: Create a makegood
      description: Create a makegood
      requestBody:
        description: createMakegood
        required: true
        content:
          application/json:
            schema:
              $ref: 'schemas/commonSchemas.yaml#/components/schemas/AcceptedResponse'
      responses:
        '202':
          description: Request processed successfully
          content:
            application/json:
              schema:
                $ref: 'schemas/commonSchemas.yaml#/components/schemas/AcceptedResponse'
        default:
          description: Unexpected error occured
          content:
            application/json:
              schema:
                $ref: 'schemas/commonSchemas.yaml#/components/schemas/Error'

  /v1/makegoods/cancel/{sgsMakegoodId}:
    delete:
      summary: Cancel a makegood
      description: Cancel a makegood
      parameters:
        - name: sgsMakegoodId
          in: path
          description: The SGS makegood Id
          required: true
      requestBody:
        description: cancelMakegood
        required: true
        content:
          application/json:
            schema:
              $ref: 'schemas/commonSchemas.yaml#/components/schemas/AcceptedResponse'
      responses:
        '202':
          description: Request processed successfully
          content:
            application/json:
              schema:
                $ref: 'schemas/commonSchemas.yaml#/components/schemas/AcceptedResponse'
        default:
          description: Unexpected error occured
          content:
            application/json:
              schema:
                $ref: 'schemas/commonSchemas.yaml#/components/schemas/Error'

  /v1/makegoods/acknowledge:
    post:
      summary: Acknowledgement of makegood processing
      description: Acknowledgement of makegood processing
      requestBody:
        description: cancelMakegood
        required: true
        content:
          application/json:
            schema:
              $ref: 'schemas/commonSchemas.yaml#/components/schemas/AcceptedResponse'
      responses:
        '200':
          description: Request processed successfully
          content:
            application/json:
              schema:
                $ref: 'schemas/commonSchemas.yaml#/components/schemas/AcceptedResponse'
        default:
          description: Unexpected error occured
          content:
            application/json:
              schema:
                $ref: 'schemas/commonSchemas.yaml#/components/schemas/Error'

  /v1/makegoods/approve:
    post:
      summary: Receive events from SGS Counterparty for approved updates to a makegood
      description: Receive events from SGS Counterparty for approved updates to a makegood
      requestBody:
        description: cancelMakegood
        required: true
        content:
          application/json:
            schema:
              $ref: 'schemas/commonSchemas.yaml#/components/schemas/AcceptedResponse'
      responses:
        '202':
          description: Request processed successfully
          content:
            application/json:
              schema:
                $ref: 'schemas/commonSchemas.yaml#/components/schemas/AcceptedResponse'
        default:
          description: Unexpected error occured
          content:
            application/json:
              schema:
                $ref: 'schemas/commonSchemas.yaml#/components/schemas/Error'

  /v1/makegoods/confirm/{sgsMakegoodId}:
    post:
      summary: Receive events from SGS Counterparty for confirmation updates to a makegood
      description: Receive events from SGS Counterparty for confirmation updates to a makegood
      parameters:
        - name: sgsMakegoodId
          in: path
          description: The SGS makegood Id
          required: true
      requestBody:
        description: cancelMakegood
        required: true
        content:
          application/json:
            schema:
              $ref: 'schemas/commonSchemas.yaml#/components/schemas/AcceptedResponse'
      responses:
        '202':
          description: Request processed successfully
          content:
            application/json:
              schema:
                $ref: 'schemas/commonSchemas.yaml#/components/schemas/AcceptedResponse'
        default:
          description: Unexpected error occured
          content:
            application/json:
              schema:
                $ref: 'schemas/commonSchemas.yaml#/components/schemas/Error'

  /v1/makegoods/notifyOpen/{sgsMakegoodId}:
    post:
      summary: Receive events from SGS Counterparty for open updates to a makegood
      description: Receive events from SGS Counterparty for open updates to a makegood
      parameters:
        - name: sgsMakegoodId
          in: path
          description: The SGS makegood Id
          required: true
      requestBody:
        description: cancelMakegood
        required: true
        content:
          application/json:
            schema:
              $ref: 'schemas/commonSchemas.yaml#/components/schemas/AcceptedResponse'
      responses:
        '202':
          description: Request processed successfully
          content:
            application/json:
              schema:
                $ref: 'schemas/commonSchemas.yaml#/components/schemas/AcceptedResponse'
        default:
          description: Unexpected error occured
          content:
            application/json:
              schema:
                $ref: 'schemas/commonSchemas.yaml#/components/schemas/Error'

  /v1/makegoods/reject/{sgsMakegoodId}:
    post:
      summary: Receive events from SGS Counterparty for rejected updates to a makegood
      description: Receive events from SGS Counterparty for rejected updates to a makegood
      parameters:
        - name: sgsMakegoodId
          in: path
          description: The SGS makegood Id
          required: true
      requestBody:
        description: cancelMakegood
        required: true
        content:
          application/json:
            schema:
              $ref: 'schemas/commonSchemas.yaml#/components/schemas/AcceptedResponse'
      responses:
        '202':
          description: Request processed successfully
          content:
            application/json:
              schema:
                $ref: 'schemas/commonSchemas.yaml#/components/schemas/AcceptedResponse'
        default:
          description: Unexpected error occured
          content:
            application/json:
              schema:
                $ref: 'schemas/commonSchemas.yaml#/components/schemas/Error'

  /v1/makegoods/subscriptions:
    post:
      summary: Create a new subscription
      description: Create a new subscription
      operationId: ordersSubscription
      requestBody:
        description: Create a new subscription
        required: true
        content:
          application/json:
            schema:
              $ref: 'schemas/makegoodsSchemas.yaml#/components/schemas/AcceptedResponse'
      responses:
        '201':
          description: Request processed successfully
          content:
            application/json:
              schema:
                $ref: 'schemas/commonSchemas.yaml#/components/schemas/subscriptionResponse'
        default:
          description: Unexpected error occured
          content:
            application/json:
              schema:
                $ref: 'schemas/commonSchemas.yaml#/components/schemas/Error'

      callbacks:
        CreateMakegoodRequest:
          '{$request.body#/resource}':
            post:
              requestBody:
                description: Contents of the CreateMakegoodRequest callback message
                required: true
                content:
                  application/json:
                    schema:
                      $ref: 'schemas/commonSchemas.yaml#/components/schemas/AcceptedResponse'
              responses:   # Expected responses to the CreateMakegoodRequest callback message
                '200':
                  description: Request processed successfully
                  content:
                    application/json:
                      schema:
                        $ref: 'schemas/commonSchemas.yaml#/components/schemas/AcceptedResponse'

        ConfirmMakegoodNotification:
          '{$request.body#/resource}':
            post:
              requestBody:
                description: Contents of the ConfirmMakegoodNotification callback message
                required: true
                content:
                  application/json:
                    schema:
                      $ref: 'schemas/commonSchemas.yaml#/components/schemas/AcceptedResponse'
              responses:   # Expected responses to the ConfirmMakegoodNotification callback message
                '200':
                  description: Request processed successfully
                  content:
                    application/json:
                      schema:
                        $ref: 'schemas/commonSchemas.yaml#/components/schemas/AcceptedResponse'

        CancelMakegoodRequest:
          '{$request.body#/resource}':
            post:
              requestBody:
                description: Contents of the CancelMakegoodRequest callback message
                required: true
                content:
                  application/json:
                    schema:
                      $ref: 'schemas/commonSchemas.yaml#/components/schemas/AcceptedResponse'
              responses: # Expected responses to the CancelMakegoodRequest callback message
                '200':
                  description: Request processed successfully
                  content:
                    application/json:
                      schema:
                        $ref: 'schemas/commonSchemas.yaml#/components/schemas/AcceptedResponse'
    get:
      summary: Enumerating subscriptions
      description: Get a list of active subscriptions
      operationId: Enumerating subscriptions
      responses:
        '200':
          description: Request processed successfully
          content:
            application/json:
              schema:
                $ref: 'schemas/commonSchemas.yaml#/components/schemas/AcceptedResponse'
        default:
          description: Unexpected error occured
          content:
            application/json:
              schema:
                $ref: 'schemas/commonSchemas.yaml#/components/schemas/Error'

  /v1/makegoods/subscriptions/{id}:
    delete:
      summary: Remove a subscription
      description: Existing subscriptions can be deleted by making a DELETE request against the subscription resource
      operationId: Remove a subscription
      parameters:
        - name: id
          in: path
          description: The subscription id
          required: true
      responses:
        '204':
          description: Subscription deleted
        default:
          description: Unexpected error occured
          content:
            application/json:
              schema:
                $ref: 'schemas/commonSchemas.yaml#/components/schemas/Error'
