openapi: "3.0.0"

info:
  version: 5.1.0
  title: Makegoods
  description: Makegoods Endpoints
  termsOfService: http://placeholderdomain.io/terms/
  contact:
    name: TIP Forum
    email: tip-mailing-list@tbd.com
    url: http://placeholderdomain.io
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: http://placeholderdomain.io/tip/v5.x.x
security:
  - bearerAuth: []

paths:
  /seller/makegood/guidelines:
    post:
      tags:
        - Seller
      summary: Seller submits a request for buyer's makegood guidelines
      description: |
        Allows the seller submits a request for buyer's makegood guidelines<br/>
        Supported Transaction Types: New
      operationId: SellerMakegoodGuidelines
      requestBody:
        description: SellerMakegoodGuidelines
        required: true
        content:
          application/json:
            schema:
              $ref: 'schemas/makegoodsSchemas.yaml#/components/schemas/SellerMakegoodGuidelines'
            example:
              New:
                value:
                  $ref: 'examples/WIP-Examples/SellerMakegoodGuidelinesNew.json'
      responses:
        '202': #Accepted
          $ref: 'schemas/commonResponses.yaml#/components/responses/Accepted'
        '400': #Bad Request
          $ref: 'schemas/commonResponses.yaml#/components/responses/BadRequest'
        '401': #Unauthorized
          $ref: 'schemas/commonResponses.yaml#/components/responses/Unauthorized'
        '403': #Forbidden
          $ref: 'schemas/commonResponses.yaml#/components/responses/Forbidden'
        '404': #Not Found
          $ref: 'schemas/commonResponses.yaml#/components/responses/NotFound'
        '405': #Not Allowed
          $ref: 'schemas/commonResponses.yaml#/components/responses/NotAllowed'
        default: #unexpected
          $ref: 'schemas/commonResponses.yaml#/components/responses/Unexpected'

  /buyer/makegood/guidelines:
    post:
      tags: 
        - Buyer
      summary: Buyer responds back to seller with list of makegood guidelines
      description: |
        Buyer responds back to seller with list of makegood guidelines 
        Supported Transaction Types: New, Change, Cancel
      operationId: BuyermakegoodGuidelines
      requestBody:
        description: Makegoods
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BuyerMakegoodGuidelines'
            examples:
              New:
                value:
                  $ref: 'examples/WIP-Examples/BuyerMakegoodGuidelinesNew.json'
              Change:
                value:
                  $ref: 'examples/WIP-Examples/BuyerMakegoodGuidelinesNew.json'
              Cancel:
                value:
                  $ref: 'examples/WIP-Examples/GenericCancel.json'
      responses:
        '200': #OK
          $ref: 'schemas/commonResponses.yaml#/components/responses/Success'
        '400': #Bad Request
          $ref: 'schemas/commonResponses.yaml#/components/responses/BadRequest'
        '401': #Unauthorized
          $ref: 'schemas/commonResponses.yaml#/components/responses/Unauthorized'
        '403': #Forbidden
          $ref: 'schemas/commonResponses.yaml#/components/responses/Forbidden'
        '404': #Not Found
          $ref: 'schemas/commonResponses.yaml#/components/responses/NotFound'
        '405': #Not Allowed
          $ref: 'schemas/commonResponses.yaml#/components/responses/NotAllowed'
        default: #unexpected
          $ref: 'schemas/commonResponses.yaml#/components/responses/Unexpected'
  
  /seller/makegood/offers:
    post:
      tags:
        - Seller
      summary: Receive Makegood Offer
      description: >
        Seller sends to Buyer one or many offer requests to support the following:
        Makegood to resolve unresolved Preemptions
        "ADU" to resolve make-up for audience shortfall
        Supported Transaction Types: New, Change, Cancel, Recall 
      operationId: SellerMakegoodOffers
      requestBody:
        description: MakegoodOffers
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SellerMakegoodOffers'
            examples:
              New:
                value:
                  $ref: 'examples/WIP-Examples/SellerMakegoodOfferNew.json'
              Change:
                value:
                  $ref: 'examples/WIP-Examples/SellerMakegoodOfferNew.json'
              Cancel:
                value:
                  $ref: 'examples/WIP-Examples/GenericCancel.json'
              Recall:
                value:
                  $ref: 'examples/WIP-Examples/GenericRecall.json'
      responses:
        '200': #OK
          $ref: 'schemas/commonResponses.yaml#/components/responses/Success'
        '400': #Bad Request
          $ref: 'schemas/commonResponses.yaml#/components/responses/BadRequest'
        '401': #Unauthorized
          $ref: 'schemas/commonResponses.yaml#/components/responses/Unauthorized'
        '403': #Forbidden
          $ref: 'schemas/commonResponses.yaml#/components/responses/Forbidden'
        '404': #Not Found
          $ref: 'schemas/commonResponses.yaml#/components/responses/NotFound'
        default: #unexpected
          $ref: 'schemas/commonResponses.yaml#/components/responses/Unexpected'

  /buyer/makegood/offers:
    post:
      tags:
        - Buyer
      summary: Buyer confirms or rejects Makegood Offers received from the seller
      description: |
        Allows the buyer to respond to an makegood offer(s) with an acceptance confirmation; this will accept all makegood offers in the request. 
        Supported Transaction Types: Reject, Confirm      
      operationId: BuyerMakegoodOffers
      requestBody:
        description: Makegood offer accept or reject request
        required: true
        content:
          application/json:
            schema:
              $ref: 'schemas/commonSchemas.yaml#/components/schemas/CancelConfirmRecallReject'
            examples:
              Confirm:
                value:
                  $ref: 'examples/WIP-Examples/GenericConfirm.json'
              Reject:
                value:
                  $ref: 'examples/WIP-Examples/GenericReject.json'
      responses:
        '200': #OK
          $ref: 'schemas/commonResponses.yaml#/components/responses/Success'
        '400': #Bad Request
          $ref: 'schemas/commonResponses.yaml#/components/responses/BadRequest'
        '401': #Unauthorized
          $ref: 'schemas/commonResponses.yaml#/components/responses/Unauthorized'
        '403': #Forbidden
          $ref: 'schemas/commonResponses.yaml#/components/responses/Forbidden'
        '404': #Not Found
          $ref: 'schemas/commonResponses.yaml#/components/responses/NotFound'
        '405': #Not Allowed
          $ref: 'schemas/commonResponses.yaml#/components/responses/NotAllowed'
        default: #unexpected
          $ref: 'schemas/commonResponses.yaml#/components/responses/Unexpected'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    BuyerMakegoodGuidelines:
      oneOf:
        - $ref: './schemas/makegoodsSchemas.yaml#/components/schemas/BuyerMakegoodGuidelines'
        - $ref: './schemas/commonSchemas.yaml#/components/schemas/CancelConfirmRecallReject'
    SellerMakegoodOffers:
      oneOf:
        - $ref: './schemas/makegoodsSchemas.yaml#/components/schemas/SellerMakegoodOffers'
        - $ref: './schemas/commonSchemas.yaml#/components/schemas/CancelConfirmRecallReject'
