openapi: "3.0.0"
info:
  version: 5.1.0
  title: Orders
  description: >-
    Allows the seller to respond back to the buyer with the detailed proposal for a given RFP
    or revised proposal; Multiple versions of a proposal can be under negotiation for
    the same campaign, but only one version may be executed; buyer must submit a "Proposal Change Request" for the last proposal version submission; seller must respond back with a Proposal Response that contains a new version number when submitting new versions.  New Proposals may be submitted without a RFP Response
  termsOfService: http://placeholderdomain.io/terms/
  contact:
    name: TIP Forum
    email: tip-mailing-list@tbd.com
    url: http://placeholderdomain.io
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: http://placeholderdomain.io
security:
  - bearerAuth: []
paths:
  /buyer/orders:
    post:
      tags:
        - Buyer
      summary: Create or Change an Order in the Seller System
      description: >-
        Allows the buyer to send the detailed information for a given order;
        execution is a summary of the sales elements details, thus allowing the seller
        to automatically create lines based on individual system's rules.
        Buyer must submit entire order for Order Change Request using the last confirmed booked
        order version response.  Seller will be responsible for deciphering change request
        from buyer.  Cancellation of order either prior to start or mid flight will be submitted
        in an order change request<br/>
        Supported Transaction Types: New, Change, Cancel, Recall
      operationId: BuyerOrders
      requestBody:
        description: Buyer Order
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BuyerOrders'
            examples:
              New:
                value:
                  $ref: 'examples/WIP-Examples/BuyerOrderNew.json'
              Change:
                value:
                  $ref: 'examples/WIP-Examples/BuyerOrderChange.json'
              Cancel:
                value:
                  $ref: 'examples/WIP-Examples/GenericCancel.json'
              Recall:
                value:
                  $ref: 'examples/WIP-Examples/GenericRecall.json'
      responses:
        '202': #Accepted
          $ref: 'schemas/commonResponses.yaml#/components/responses/Accepted'
        '400': #Bad Request
          $ref: 'schemas/commonResponses.yaml#/components/responses/BadRequest'
        '401': #Unauthorized
          $ref: 'schemas/commonResponses.yaml#/components/responses/Unauthorized'
        '403': #Forbidden
          $ref: 'schemas/commonResponses.yaml#/components/responses/Forbidden'
        '404': #Not Found
          $ref: 'schemas/commonResponses.yaml#/components/responses/NotFound'
        '405': #Not Allowed
          $ref: 'schemas/commonResponses.yaml#/components/responses/NotAllowed'
        default: #unexpected
          $ref: 'schemas/commonResponses.yaml#/components/responses/Unexpected'
  /seller/orders:
    post:
      tags:
        - Seller
      summary: Seller Reject or Confirm an order
      description: >-
        Allows the seller to respond with a reject or confirm of an order
      operationId: SellerOrders
      requestBody:
        description: Seller order confirm or reject
        required: true
        content:
          application/json:
            schema:
              $ref: './schemas/commonSchemas.yaml#/components/schemas/CancelConfirmRecallReject'
            examples:
              Reject:
                value:
                  $ref: 'examples/WIP-Examples/GenericReject.json'
              Confirm:
                value:
                  $ref: 'examples/WIP-Examples/GenericConfirm.json'
      responses:
        '202': #Accepted
          $ref: 'schemas/commonResponses.yaml#/components/responses/Accepted'
        '400': #Bad Request
          $ref: 'schemas/commonResponses.yaml#/components/responses/BadRequest'
        '401': #Unauthorized
          $ref: 'schemas/commonResponses.yaml#/components/responses/Unauthorized'
        '403': #Forbidden
          $ref: 'schemas/commonResponses.yaml#/components/responses/Forbidden'
        '404': #Not Found
          $ref: 'schemas/commonResponses.yaml#/components/responses/NotFound'
        '405': #Not Allowed
          $ref: 'schemas/commonResponses.yaml#/components/responses/NotAllowed'
        default: #unexpected
          $ref: 'schemas/commonResponses.yaml#/components/responses/Unexpected'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    BuyerOrders:
      description: |
          The Buyer can perform the following operations:
          <li>New or Change - Use the Buyer orders object
          <li>Cancel or Recall - Use the Generic object to Cancel or Recall
      oneOf:
        - $ref: './schemas/ordersSchemas.yaml#/components/schemas/BuyerOrders'
        - $ref: './schemas/commonSchemas.yaml#/components/schemas/CancelConfirmRecallReject'    