openapi: "3.0.0"
info:
  version: 5.1.0
  title: Proposals
  description: |
    * Allows the seller to respond back to the buyer with the detailed proposal for a given RFP or revised proposal;
    Multiple versions of a proposal can be under negotiation for the same campaign, but only one version may be executed; buyer must submit a
    "Proposal Change Request" for the last proposal version submission; seller must respond back with a Proposal Response that contains a new
    version number when submitting new versions.  New Proposals may be submitted without a RFP Response
  termsOfService: http://placeholderdomain.io/terms/
  contact:
    name: TIP Initiative
    email: tipinitiative@frontrowadvisory.com
    url: http://placeholderdomain.io
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: http://placeholderdomain.io
security:
  - bearerAuth: []
paths:
  /seller/proposals:
    post:
      tags:
        - Seller
      summary: Create or Change a proposal in the buyers system
      description: >-
        Allows the seller to respond back to the buyer with the detailed proposal
        for a given RFP or revised proposal; Multiple versions of a proposal can be under
        negotiation for the same campaign, but only one version may be executed;
        buyer must submit a "Proposal Change Request" for the last proposal version submission;
        seller must respond back with a Proposal Response that contains a new version number
        when submitting new versions.  New Proposals may be submitted without a RFP Response<br/>
        <ul>
        <li>New - Create New proposal based on RFP or unsolicited</li>
        <li>Change - Make changes to previously sent proposal or responding to proposed chages suggested by the buyer</li>
        <li>Cancel - sending a cancel assumes that seller no longer wants the buyer to consider the proposal</li>
        <li>Recall - sending a Recall is asking the buyer to ignore changes communicated in the prior exchange.</li>
        <ul>
      operationId: SellerProposals
      requestBody:
        description: Create, Change, Cancel, or Recall a proposal in the buyers system
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SellerProposals'
            examples:
              New:
                value:
                  $ref: 'examples/SellerProposalNew.json'
              Change:
                value:
                  $ref: 'examples/SellerProposalChange.json'
              Cancel:
                  value:
                    $ref: 'examples/GenericCancel.json'
              Recall:
                  value:
                    $ref: 'examples/GenericRecall.json'
      responses:
        '202': #OK
          $ref: 'schemas/commonResponses.yaml#/components/responses/Accepted'
        '400': #Bad Request
          $ref: 'schemas/commonResponses.yaml#/components/responses/BadRequest'
        '401': #Unauthorized
          $ref: 'schemas/commonResponses.yaml#/components/responses/Unauthorized'
        '403': #Forbidden
          $ref: 'schemas/commonResponses.yaml#/components/responses/Forbidden'
        '404': #Not Found
          $ref: 'schemas/commonResponses.yaml#/components/responses/NotFound'
        '405': #Not Allowed
          $ref: 'schemas/commonResponses.yaml#/components/responses/NotAllowed'
        default: #unexpected
          $ref: 'schemas/commonResponses.yaml#/components/responses/Unexpected'
  /buyer/proposals:
    post:
      tags:
        - Buyer
      summary: Buyer change a proposal in the seller's system
      description: >-
        Allows the buyer to respond back to the seller with the proposed changeds for a given proposal;
        Multiple versions of a proposal can be under negotiation for the same campaign,
        but only one version may be executed; buyer must submit a 'Proposal Change' for the last proposal version submitted;
        seller must respond back with a Proposal that contains a new version number when submitting the change<br/>
        Supported Transaction Type: Change, Recall
      operationId: BuyerProposals
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SellerProposals'
            examples:
              Change:
                value:
                  $ref: 'examples/SellerProposalChange.json'
              Recall:
                  value:
                    $ref: 'examples/GenericRecall.json'
      responses:
        '202': #OK
          $ref: 'schemas/commonResponses.yaml#/components/responses/Accepted'
        '400': #Bad Request
          $ref: 'schemas/commonResponses.yaml#/components/responses/BadRequest'
        '401': #Unauthorized
          $ref: 'schemas/commonResponses.yaml#/components/responses/Unauthorized'
        '403': #Forbidden
          $ref: 'schemas/commonResponses.yaml#/components/responses/Forbidden'
        '404': #Not Found
          $ref: 'schemas/commonResponses.yaml#/components/responses/NotFound'
        '405': #Not Allowed
          $ref: 'schemas/commonResponses.yaml#/components/responses/NotAllowed'
        default: #unexpected
          $ref: 'schemas/commonResponses.yaml#/components/responses/Unexpected'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    SellerProposals:
      description: Request Body for the endpoint varies based on Transaction type
      oneOf:
        - $ref: './schemas/proposalSchemas.yaml#/components/schemas/SellerProposals'
        - $ref: './schemas/commonSchemas.yaml#/components/schemas/CancelConfirmRecallReject'
