openapi: "3.0.0"

components:
 securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: []

info:
  version: 5.x.x
  title: Proposal
  description: |
    * Allows the seller to respond back to the buyer with the detailed proposal for a given RFP or revised proposal;
    Multiple versions of a proposal can be under negotiation for the same campaign, but only one version may be executed; buyer must submit a
    "Proposal Change Request" for the last proposal version submission; seller must respond back with a Proposal Response that contains a new
    version number when submitting new versions.  New Proposals may be submitted without a RFP Response
  termsOfService: http://placeholderdomain.io/terms/
  contact:
    name: TIP Initiative
    email: tipinitiative@frontrowadvisory.com
    url: http://placeholderdomain.io
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: http://placeholderdomain.io

paths:
  /seller/proposal:
    post:
      tags:
        - Seller
      summary: Create or Change a proposal in the buyers system
      description: >-
        Allows the seller to respond back to the buyer with the detailed proposal 
        for a given RFP or revised proposal; Multiple versions of a proposal can be under
         negotiation for the same campaign, but only one version may be executed; 
         buyer must submit a "Proposal Change Request" for the last proposal version submission; 
         seller must respond back with a Proposal Response that contains a new version number 
         when submitting new versions.  New Proposals may be submitted without a RFP Response
      operationId: createChangeProposal
      requestBody:
        description: Create or Change a proposal in the buyers system
        required: true
        content:
          application/json:
            schema:
              $ref: 'schemas/proposalSchemas.yaml#/components/schemas/SellerProposal'
      responses:
        '200': #OK
          $ref: 'schemas/commonResponses.yaml#/components/responses/Success'
        '400': #Bad Request
          $ref: 'schemas/commonResponses.yaml#/components/responses/BadRequest'
        '401': #Unauthorized
          $ref: 'schemas/commonResponses.yaml#/components/responses/Unauthorized'
        '403': #Forbidden
          $ref: 'schemas/commonResponses.yaml#/components/responses/Forbidden'
        '404': #Not Found
          $ref: 'schemas/commonResponses.yaml#/components/responses/NotFound'
        '405': #Not Allowed
          $ref: 'schemas/commonResponses.yaml#/components/responses/NotAllowed'
        default: #unexpected
          $ref: 'schemas/commonResponses.yaml#/components/responses/Unexpected'
  /seller/proposal/cancel:
    post:
      tags:
        - Seller
      summary: Cancel a proposal in the buyer's system
      description: >-
        Cancel a proposal in the buyer's system
        This endpoint allows the seller to request from the buyer to cancel and ignore
        a previously communicated proposal request. As Follows:<br/>
        NOTE#1:originalTransactionId values needs to indicate which request is to be cancelled.<br/>
        NOTE#2: transactionId.transactionType = Cancel<br/>
        NOTE#3: originalTransactionId.transactionId must refer to the transaction in question to be cancelled
      operationId: cancelProposal
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: 'schemas/commonSchemas.yaml#/components/schemas/TransactionHeader'
      responses:
        '200': #OK
          $ref: 'schemas/commonResponses.yaml#/components/responses/Success'
        '400': #Bad Request
          $ref: 'schemas/commonResponses.yaml#/components/responses/BadRequest'
        '401': #Unauthorized
          $ref: 'schemas/commonResponses.yaml#/components/responses/Unauthorized'
        '403': #Forbidden
          $ref: 'schemas/commonResponses.yaml#/components/responses/Forbidden'
        '404': #Not Found
          $ref: 'schemas/commonResponses.yaml#/components/responses/NotFound'
        '405': #Not Allowed
          $ref: 'schemas/commonResponses.yaml#/components/responses/NotAllowed'
        default: #unexpected
          $ref: 'schemas/commonResponses.yaml#/components/responses/Unexpected'
