openapi: "3.0.0"
info:
  version: 6.0.0
  title: Request For Proposals (RFPS)
  description: Allows the buyer to submit a Request for Proposal (RFP) to the seller with overall media budget, goal and makegood terms and optionally include specific detailed inventory requests
  termsOfService: http://placeholderdomain.io/terms/
  contact:
    name: TIP Initiative
    email: tipinitiative@frontrowadvisory.com
    url: http://placeholderdomain.io
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: http://placeholderdomain.io
security:
  - bearerAuth: []
paths:
  /buyer/rfps:
    post:
      tags:
        - Buyer
      summary: Allows the buyer to submit a Request for Proposal (RFP) to the seller with media budget, goals and overall terms
      description: >-
        This endpoint resides on the seller side. The purpose of the endpoint is to allow the buyer to send new RFP or cancel
        a previously sent request.<br/>
        Supported Transaction Types:<br/>
        <ul>
        <li>New - Send a new Request for Proposal using the BuyerRPFS schema</li>
        <li>Cancel - Send a cacellation of previously sent request</li>
        </ul>
      operationId: BuyerRFPS
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BuyerRFPSRequest'
            examples:
              New:
                value:
                  $ref: 'examples\6.0.0\Buyer\JSON\RFPSNew.json'
              Cancel:
                value:
                  $ref: 'examples\6.0.0\Buyer\JSON\RFPSCancel.json'
          application/xml:
            schema:
              $ref: '#/components/schemas/BuyerRFPSRequest'
            examples:
              New:
                value:
                  $ref: 'examples\6.0.0\Buyer\XML\RFPSNew.xml'
              Cancel:
                value:
                  $ref: 'examples\6.0.0\Buyer\XML\RFPSCancel.xml'
      responses:
        '202': #OK
          $ref: 'schemas/commonResponses.yaml#/components/responses/Accepted'
        '400': #Bad Request
          $ref: 'schemas/commonResponses.yaml#/components/responses/BadRequest'
        '401': #Unauthorized
          $ref: 'schemas/commonResponses.yaml#/components/responses/Unauthorized'
        '403': #Forbidden
          $ref: 'schemas/commonResponses.yaml#/components/responses/Forbidden'
        '404': #Not Found
          $ref: 'schemas/commonResponses.yaml#/components/responses/NotFound'
        '405': #Not Allowed
          $ref: 'schemas/commonResponses.yaml#/components/responses/NotAllowed'
        default: #unexpected
          $ref: 'schemas/commonResponses.yaml#/components/responses/Unexpected'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    BuyerRFPSRequest:
      description: Request Body for the endpoint varies based on Transaction type
      oneOf:
        - $ref: 'schemas/rfpsSchemas.yaml#/components/schemas/BuyerRFPS'
        - $ref: 'schemas/commonSchemas.yaml#/components/schemas/CancelConfirmRecallReject'
      xml:
        name: BuyerRFPSRequest
